### ISSUE TITLE
Rcpp installation fails

### ISSUE THREAD

**Issue by subhomoyghosh** [RcppCore/Rcpp#843] opened 2018-04-03 21:47 UTC
Hi, 

  I am trying to install the new version of Rcpp but it fails to compile. Please see below the error message. Will appreciate any help.

Thanks,
SG

###################

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("Rcpp")
Installing package into ‘/home/guest/sng8/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.16.tar.gz'
Content type 'application/x-gzip' length 3763400 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG -std=c++11     -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
Date.cpp:31:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/guest/sng8/R/x86_64-pc-linux-gnu-library/3.4/Rcpp’
Warning in install.packages :
  installation of package ‘Rcpp’ had non-zero exit status

######

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.1.14   

###############

Machine Info: 

uname -a
Linux el-f-854970 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu

Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 6.3.0-18ubuntu2 14.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170519 (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04)

**Comment by eddelbuettel** [comment] 2018-04-03 21:55
Come on now.  Please see 
- all the [CRAN checks on Rcpp](https://cloud.r-project.org/web/checks/check_results_Rcpp.html) 
- as you're on Linux, [all the Debian builds of 0.12.16](https://buildd.debian.org/status/package.php?p=rcpp&suite=unstable) 
- all [our Travis builds](https://travis-ci.org/RcppCore/Rcpp/builds)

Maybe your machine runs out of ram.  You didn't say.  We can't tell.  But you need to do a little more to "show" a problem when it builds everywhere else.

**Comment by eddelbuettel** [comment] 2018-04-03 21:56
And see [this PPA with binaries](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u) if you really fail.

**Comment by eddelbuettel** [comment] 2018-04-03 22:11
Lastly, there may be something wrong with your R version. See how build below (or any other one, see eg the Travis logs per the link above) uses `-I../inst/include` -- you need to figure out why your R version does not do that.

```R
R> install.packages("Rcpp")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.16.tar.gz'
Content type 'application/x-gzip' length 3763400 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c Date.cpp -o Date.o
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c Module.cpp -o Module.o
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c Rcpp_init.cpp -o Rcpp_init.o
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c api.cpp -o api.o
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c attributes.cpp -o attributes.o
ccache g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O3 -Wall -pipe  -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c barrier.cpp -o barrier.o
ccache g++ -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)

The downloaded source packages are in
        ‘/tmp/Rtmp3tf8Zq/downloaded_packages’
R> 
```

Your compilation also defaults to using C++11 which is not expected.  I think the issue is self-inflicted (did you mess with `~/.R/Makevars` ?  other env vars) and will close this.

**Closed by eddelbuettel** 2018-04-03 22:11 UTC

**Comment by subhomoyghosh** [comment] 2018-04-03 22:28
I see. My  ~/.R/Makevars is 

CC=gcc
CXX=g++
FC=/usr/bin/gfortran
F77=/usr/bin/gfortran 
PKG_LIBS = -fopenmp -lgomp
PKG_CFLAGS= -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp
CFLAGS= -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp

The build example is very helpful. Yes, I might have messed up somewhere. Thanks!

**Comment by eddelbuettel** [comment] 2018-04-03 22:31
FWIW here is (an edited) portion of mine 

```
## edd 03 Mar 2009                 emacs please make this a -*- mode: Makefile; -*-

PEDANTIC=-pedantic -Werror
PEDANTIC=

XTRAFLAGS=-Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations
#XTRAFLAGS=

## for C code
CFLAGS=               -g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -std=gnu99 -march=native

## for C++ and C++11 code
CXXFLAGS=            	-g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -march=native
CXX1XFLAGS=		-g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -march=native
CXX11FLAGS=		-g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -march=native
CXX14FLAGS=		-g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -march=native

FLAGS=-Wall -O3

# just a test before RcppArmadillo undef'ed thispp
#PKG_CPPFLAGS=        -UNDEBUG

## for Fortran code
FFLAGS=-O3 -g0 -Wall -pipe
## for Fortran 95 code
FCFLAGS=-O3 -g0 -Wall -pipe

#VER=-4.9
VER=
CCACHE=ccache
CC=$(CCACHE) gcc$(VER)
CXX=$(CCACHE) g++$(VER)
CXX11=$(CCACHE) g++$(VER) #-std=c++11
CXX14=$(CCACHE) g++$(VER) #-std=c++14

STRIP=-Wl,-S
SHLIB_CXXLDFLAGS = $(STRIP) -shared
SHLIB_CXX11LDFLAGS = $(STRIP) -shared
SHLIB_CXX14LDFLAGS = $(STRIP) -shared
SHLIB_FCLDFLAGS = $(STRIP) -shared
SHLIB_LDFLAGS = $(STRIP) -shared

FC=$(ccache) gfortran
F77=$(ccache) gfortran
F95=$(ccache) gfortran

## Works again with 16.10
#CXX=ccache clang++
#CXX11=ccache clang++ -std=c++11
#CXX14=ccache clang++ -std=c++14
#CC=ccache clang
#SHLIB_CXXLD=clang
#CXXFLAGS=-Wall -O3 
```

**Comment by subhomoyghosh** [comment] 2018-04-04 12:55
Sorry for being delayed in responding here! It is my office machine. So, I removed line 5 & 6 of my Makevars as you suggested but it still defaulting to C++11 and failing with same error. I also used your Makevars (since I had ccache installed from before) but couldn't get rid of C++11. Any suggestion for me? 

#############################

> install.packages("Rcpp")
Installing package into ‘/home/guest/sng8/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.16.tar.gz'
Content type 'application/x-gzip' length 3763400 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
ccache g++ -I/usr/share/R/include -DNDEBUG -std=c++11     -fpic  -g -O3 -Wall -pipe -pedantic -Werror -Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-deprecated-declarations -march=native -c Date.cpp -o Date.o
Date.cpp:31:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/guest/sng8/R/x86_64-pc-linux-gnu-library/3.4/Rcpp’

**Comment by eddelbuettel** [comment] 2018-04-04 13:02
Simplify as much as you can.  Try, for starters, without `.R/Makevars`.  

Your compilation line _still_ shows that the `PKG_CPPFLAGS` I set and which we need is overridden/erased.  You need to figure out why/where.  Below `$RHOME`, an env var, in your `~/.R/` ...

**Comment by subhomoyghosh** [comment] 2018-04-04 13:28
No-Makevars shows same problem. After I set PKG_CPPFLAGS to be empty (to overwrite) with nothing else in Makevars, it still shows same problem although it doesn't show C++11 anymore.

**Comment by eddelbuettel** [comment] 2018-04-04 14:06
See `help(Startup)` and other pages, there are A LOT of places where you can set things, causing the side effect you see.  I would now look into R's own `Makeconf` (in `etc/` inside the R installation).

**Comment by kevinushey** [comment] 2018-04-04 16:29
The variables prefixed with `PKG_` are for use by the package itself in its own `src/Makevars[.win]` -- e.g. `Rcpp` uses this to ensure `-I../inst/include` is passed to the compiler so that compilation can succeed. See:

https://github.com/RcppCore/Rcpp/blob/960948d1cbcb78e530fcbcf4bac8c17ded0684df/src/Makevars#L1

You shouldn't modify those in your own local `Makevars` file. If you do, you should only append to the existing values, but you still risk breaking compilation of R packages. You should only modify the non-`PKG_`-prefixed Makevars variables.

**Comment by eddelbuettel** [comment] 2018-04-04 16:36
Also see Writing R Extensions for what to set, and not set.  I guess I misread your 'to be empty' -- that is guaranteed to *cripple* the build just as you see.  It will not find the header file.  Which is *precisely* the error you have been fighting since day one.  

![image](https://user-images.githubusercontent.com/673121/38321193-6e8f4dd2-37fc-11e8-88cf-c1842303f616.png)

**Comment by subhomoyghosh** [comment] 2018-04-04 18:45
Well, I removed the Makevars file and reinstalled R by synaptic package manager. It is showing me same error.

**Comment by eddelbuettel** [comment] 2018-04-04 19:01
Then you are still doing something wrong. 

Here is something as standard as it can get: Docker image `r-base`. No user settings.

```
edd@rob:~$ docker run --rm -ti r-base /bin/bash
root@602f2ece7126:/# R

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("Rcpp")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.16.tar.gz'
Content type 'application/x-gzip' length 3763400 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
g++  -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier.cpp -o barrier.o
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)

The downloaded source packages are in
	‘/tmp/RtmpGpNzOj/downloaded_packages’
> library(Rcpp)
> 
```

**Comment by subhomoyghosh** [comment] 2018-04-09 16:12
Just wanted to update that although I couldn't find out why that installation failed even after removing Makevars, but finally I got around the problem by building R from source in a different directory other than /usr/bin/.  I could install Rcpp and few other packages with no problems.
