### ISSUE TITLE
Compilation of v0.12.0 on Windows (Win8.1 and Win7)

### ISSUE THREAD

**Issue by R-Hertel** [RcppCore/Rcpp#334] opened 2015-07-25 22:27 UTC
Dear developers,

I have encountered an error today when I tried to compile the source of version 0.12.0 on Windows. The same error occured on two of my computers, one with Win7 and the other with Win 8.1. The previous version 0.11.6 is installed in both cases and it works fine. On my computers with ubuntu the upgrade worked perfectly.

In Windows, I tried to install the new Rcpp version within an `R` session by using 

    > install.packages("Rcpp", type = "source", dependencies = T) 
The output that I obtain during the installation is the following:

    Installing package into ‘C:/Users/rhert_000/Documents/R/win-library/3.2’
    (as ‘lib’ is unspecified)
    also installing the dependency ‘highlight’

    trying URL 'https://cran.rstudio.com/src/contrib/highlight_0.4.7.tar.gz'
    Content type 'application/x-gzip' length 356443 bytes (348 KB)
    downloaded 348 KB

    trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.0.tar.gz'
    Content type 'application/x-gzip' length 2297548 bytes (2.2 MB)
    downloaded 2.2 MB

    * installing *source* package 'highlight' ...
    ** package 'highlight' correctement décompressé et sommes MD5 vérifiées
    ** libs

    *** arch - i386
    Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="highlight.dll" OBJECTS="ASBeautifier.o ASEnhancer.o ASFormatter.o ASResource.o ASStreamIterator.o Matcher.o Pattern.o ansigenerator.o bbcodegenerator.o codegenerator.o configurationreader.o ctagsreader.o datadir.o documentstyle.o elementstyle.o highlight_wrapper.o htmlgenerator.o languagedefinition.o latexgenerator.o platform_fs.o preformatter.o render.o rtfgenerator.o stringtools.o stylecolour.o svggenerator.o texgenerator.o xhtmlgenerator.o xmlgenerator.o xterm256generator.o"' renvoie un statut 127
    ERROR: compilation failed for package 'highlight'
    * removing 'C:/Users/rhert_000/Documents/R/win-library/3.2/highlight'
    Warning in install.packages :
    running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\rhert_000\Documents\R\win-library\3.2" C:\Users\RHERT_~1\AppData\Local\Temp\RtmpmQ2HQa/downloaded_packages/highlight_0.4.7.tar.gz' had status 1
    Warning in install.packages :
      installation of package ‘highlight’ had non-zero exit status
    * installing *source* package 'Rcpp' ...
    ** package 'Rcpp' correctement décompressé et sommes MD5 vérifiées
    ** libs

    *** arch - i386
    Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="Rcpp.dll" OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o"' renvoie un statut 127
    ERROR: compilation failed for package 'Rcpp'
    * removing 'C:/Users/rhert_000/Documents/R/win-library/3.2/Rcpp'
    * restoring previous 'C:/Users/rhert_000/Documents/R/win-library/3.2/Rcpp'
    Warning in install.packages :
      running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\rhert_000\Documents\R\win-library\3.2" C:\Users\RHERT_~1\AppData\Local\Temp\RtmpmQ2HQa/downloaded_packages/Rcpp_0.12.0.tar.gz' had status 1
    Warning in install.packages :
    installation of package ‘Rcpp’ had non-zero exit status

I apologize for the French locale, but I trust that this will not present a serious obstacle in interpreting the error message (status 127). 

I would be very thankful for indications on how this problem could be resolved. Please let me know if you require further information, e.g., concerning the system configuration. Thanks in advance.

Best regards,
Riccardo Hertel

**Comment by kevinushey** [comment] 2015-07-25 22:38
Thanks for the report -- I can reproduce this on my Windows VM; I'll see if I can figure out what's going on.

**Comment by kevinushey** [comment] 2015-07-25 22:42
Okay, here's what's going on:

1. The binaries for Windows have not yet been built, so by default you instead get served a source tarball of Rcpp 0.12.0.

2. R attempts to build Rcpp from source, but fails -- this almost certainly occurs because you do not have Rtools installed, or it's not on the `PATH`.

In my case, I replicated this because I too did not have Rtools on the `PATH` -- so please try installing [Rtools 3.2](https://cran.r-project.org/bin/windows/Rtools/Rtools32.exe) and setting up your PATH appropriately, or wait until Windows binaries make their way to CRAN.

Thanks,
Kevin

**Comment by eddelbuettel** [comment] 2015-07-25 23:07
Please disentangle:
+ start with `install.package("highlight")`, and all other build-time dependencies
+ then install `Rcpp` from source as you attempted.
The log [to the most recent win-builder build log](http://win-builder.r-project.org/F1ZY4AdXhSQM) is here and will remain accessible for another day or two after which it gets deleted.  You can also use that link **now** to fetch a pre-built binary.

For what it is worth, here is the log of that last build:

> From: Uwe.Ligges@R-Project.org
To: edd@debian.org
Cc: Uwe.Ligges@R-Project.org
Subject: winbuilder: Package Rcpp_0.12.0.tar.gz has been checked and built
Date: Sat, 25 Jul 2015 01:51:35 +0200
> 
> Dear package maintainer,
 > 
> this notification has been generated automatically.
Your package Rcpp_0.12.0.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
http://win-builder.r-project.org/F1ZY4AdXhSQM
The files will be removed after roughly 72 hours.
Installation time in seconds: 68
Check time in seconds: 206
Check result: OK
R version 3.2.1 (2015-06-18)
>  
> All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)

**Comment by eddelbuettel** [comment] 2015-07-26 03:42
And now I just got

> Date: Sun, 26 Jul 2015 04:28:30 +0200 
From: Uwe.Ligges@R-Project.org
To: edd@debian.org
Cc: Uwe.Ligges@R-Project.org
Subject: Package Rcpp_0.12.0.tar.gz has been built for Windows
>                                                                                                              
> Dear package maintainer,                                
>                                                                  
> this notification has been generated automatically. 
Your package Rcpp_0.12.0.tar.gz has been built for Windows and
will be published within 24 hours in the corresponding CRAN directory.
R version 3.2.1 (2015-06-18)
>
> All the best,
> Uwe Ligges 
(Maintainer of binary packages for Windows)

so I think we can close this.

**Closed by eddelbuettel** 2015-07-26 03:42 UTC

**Comment by R-Hertel** [comment] 2015-07-26 06:59
Thank you very much for the rapid and detailed help. After installing Rtools 3.2 and setting the PATH everything worked perfectly.
