### ISSUE TITLE
naming function arguments either "major" or "minor" prevents compilation

### ISSUE THREAD

**Issue by jackwasey** [RcppCore/Rcpp#227] opened 2015-01-14 16:12 UTC
```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
int timesTwo(int major) {
   return major * 2;
}
```
I'm far from an expert, but I think the following generated code appears to the compiler as a function call to `major`.
_RcppExports.cpp_
```
Rcpp::traits::input_parameter< int >::type major(majorSEXP )
```
I don't see anything anywhere about `major` or `minor` being reserved keywords in C++, the STL or Rcpp.

**Comment by eddelbuettel** [comment] 2015-01-14 16:41
Confirmed:
```{.r}
cppFunction("int foo(int maj) { return(2*maj); }")
```
works where 
```{.r}
cppFunction("int foo(int major) { return(2*major); }")
```
fails -- and I also fail to see where the identifier comes from.

**Comment by romainfrancois** [comment] 2015-01-14 16:52
Works fine for me on OS X with clang: 

```
> require(Rcpp)
Le chargement a nécessité le package : Rcpp
> cppFunction("int foo(int major) { return(2*major); }")
> foo(2L)
[1] 4
```

**Comment by romainfrancois** [comment] 2015-01-14 17:27
I get this on ubuntu: 

```
> Rcpp:::areMacrosDefined( c( "major", "minor" ) )
major minor 
 TRUE  TRUE 
```

**Comment by eddelbuettel** [comment] 2015-01-14 20:19
It fails for me with clang++ and g++:

```{.r}
R> cppFunction("int foo(int major) { return(2*major); }")
file22fc2782fa4f.cpp: In function ‘SEXPREC* sourceCpp_42708_foo(SEXP)’:                                                                                                                                                                    
file22fc2782fa4f.cpp:17:28: error: ‘major’ was not declared in this scope
         int __result = foo(major);
                            ^
make: *** [file22fc2782fa4f.o] Error 1
ccache g++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c \
file22fc2782fa4f.cpp -o file22fc2782fa4f.o
/usr/lib/R/etc/Makeconf:142: recipe for target 'file22fc2782fa4f.o' failed
Error in sourceCpp(code = code, env = env, rebuild = rebuild, showOutput = showOutput,  :
  Error 1 occurred building shared library.
R> 
R> cppFunction("int foo(int major) { return(2*major); }")
file22fc2782fa4f.cpp:17:28: error: use of undeclared identifier 'major'
        int __result = foo(major);
                           ^
1 error generated.
make: *** [file22fc2782fa4f.o] Error 1
clang++ -I/usr/share/R/include -DNDEBUG    -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c fil\
e22fc2782fa4f.cpp -o file22fc2782fa4f.o
/usr/lib/R/etc/Makeconf:142: recipe for target 'file22fc2782fa4f.o' failed
Error in sourceCpp(code = code, env = env, rebuild = rebuild, showOutput = showOutput,  :
  Error 1 occurred building shared library.
R> 
```

**Comment by eddelbuettel** [comment] 2015-01-14 20:33
And if I run 'g++ -E ...' I end up with 120k lines, but none defining major.  Hm.

**Comment by kevinushey** [comment] 2015-01-14 21:20
On OS X with `clang`, I don't see the macros:

```
> Rcpp:::areMacrosDefined(c("major", "minor"))
major minor 
FALSE FALSE 
```

Yet, with a fresh install of Rcpp 0.11.3 from CRAN on Ubuntu, I see:

```
> Rcpp:::areMacrosDefined(c("major", "minor"))
major minor 
TRUE TRUE 
```

It appears `R CMD SHLIB` is actually forcing these defines. With the file `test.cpp`:

```
#include <R.h>
#include <Rinternals.h>

extern "C" SEXP test() {
#ifdef major
    printf("major defined\n");
#endif
    return R_NilValue;
}
```

running this command:

    R CMD SHLIB test.cpp && R -e "dyn.load('test.so'); .Call('test')"

gives

    major defined

on stdout. So this is indeed an R bug.

**Comment by kevinushey** [comment] 2015-01-15 01:56
I've reported this [to R](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16159). There are obvious workarounds but this isn't an Rcpp problem.

**Comment by kevinushey** [comment] 2015-01-15 06:02
More information on the issue here: http://stackoverflow.com/questions/22240973/major-and-minor-macros-defined-in-sys-sysmacros-h-pulled-in-by-iterator

I think the onus is on us to be 'good citizens' and undefine these stupid macros if encountered. We could try using the `#pragma push_macro` and `#pragma pop_macro` trick to avoid such leakage.

**Comment by eddelbuettel** [comment] 2015-01-16 14:04
So where are we with this?  Do this, but turn off the warning messages (unless, say, in DEBUG mode)?

**Comment by jjallaire** [comment] 2015-01-16 20:34
I would say don't do it because it's out of scope, but Kevin if you feel
strongly go ahead (but without warnings)

On Fri, Jan 16, 2015 at 9:04 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by kevinushey** [comment] 2015-01-16 20:49
I still feel somewhat strongly about working around it. I updated the PR to:

1. Never give warnings, and
2. Use the `#pragma push_macro() / pop_macro()` to preserve any pre-defined `major`, `minor`, `makedev` macros (to ensure they aren't clobbered by `<sys/sysmacros.h>`).

So we don't need warnings, and we preserve pre-existing macros if necessary.

**Comment by eddelbuettel** [comment] 2015-01-16 21:07
I can live with that.  @jjallaire, what's your take?

**Comment by jjallaire** [comment] 2015-01-16 21:08
I'm in! (just merged)

On Fri, Jan 16, 2015 at 4:07 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment] 2015-01-16 21:27
Cool beans.

**Closed by eddelbuettel** 2015-01-16 21:27 UTC
