### ISSUE TITLE
Rcpp::stop causes segfault on Solaris

### ISSUE THREAD

**Issue by dbaston** [RcppCore/Rcpp#1159] opened 2021-04-26 01:33 UTC
I'm trying to troubleshoot a package that uses Rcpp and is failing the CRAN checks for Solaris. The CRAN checks are segfaulting when my package calls `Rcpp::stop()`. I have verified the behavior using the R-hub builder and by building a Solaris VM using the instructions from https://github.com/r-hub/solarischeck. The problem only occurs in the Oracle Development Suite variant of the R-hub builder, which I understand matches the CRAN configuration. There is no problem when using gcc on Solaris.

Here is a minimal example:

```
> doIt <- Rcpp::cppFunction('void doIt() { Rcpp::stop("Message"); }');
> doIt()

 *** caught segfault ***
address 0, cause 'memory not mapped'

Traceback:
 1: .Call(<pointer: fd189f30>)
 2: doIt()
```

`sessionInfo` output is as follows:

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: i386-pc-solaris2.10 (32-bit)
Running under: Solaris 10

Matrix products: default
BLAS:   /opt/R/R-4.0.5/lib/R/lib/libRblas.so
LAPACK: /opt/R/R-4.0.5/lib/R/lib/libRlapack.so

locale:
[1] /en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Rcpp_1.0.6

loaded via a namespace (and not attached):
[1] compiler_4.0.5
```

**Comment by eddelbuettel** [comment] 2021-04-26 02:50
We have as much access to Solaris machines as you do, so you're guess is as good as ours. I just spot-checked two of my Rcpp-using machines: they are both fine on Solaris per the CRAN checks.  (That said all this is a bit of a mystery as I know that 'the powers that be' do not test some other packages, or let them be with not building for lack of build-depends.)   

While this sounds like chickening out, but maybe your tests ... should not call `stop()` to avoid issues there?  That said, I am fairly sure I have unit tests ending that way but they may all be wrapped in predicates expecting errors leading to a pass on each occurrence.

**Comment by eddelbuettel** [comment] 2021-04-26 03:18
I may have misread what you did up there. In short, it may not matter.  

So here is what I just did
1.  Call `kitten.r -p callstop -t rcpp` to create a quick ad-hoc i) package using ii) Rcpp and iii) tinytest.  This may use features of my `pkgKitten` package (called via the `kitten.r` frontend from package `littler`) only in its GitHub repo, and/or only in the GitHub version of `littler.  In any event, _those change_ are quick conveniences. You can always use `Rcpp::Rcpp.package.skeleton()` too which is related.
2.  Add a one line function similar to your example to just call `Rcpp::stop("some text")`.  Call `compileAttributes()`.
3.  Call that one function from a `tinytest` test function via `expect_errror()`.
4. Submit to the RHub builder's Solaris box (via another helper script from littler, `cos.r`).

It passes just fine:  https://builder.r-hub.io/status/callstop_1.0.tar.gz-6fa5f7bf314f4e57b27dabd56d9f4e91

If it helps you I can tar up the demo package for you.   So in short I am not sure we have issue here, at least not as described.  Maybe you describe your actual issue, assuming there is one, with a minimally reproducible example?

**Comment by dbaston** [comment] 2021-04-26 14:34
Thanks for looking into this. As I mentioned, the Solaris gcc builds are OK; the problem only shows up when the Oracle compiler is used (as is the case on CRAN). I resubmitted your `callstop` package to R-hub using the Oracle configuration and it segfaults: https://builder.r-hub.io/status/callstop_1.0.tar.gz-69460717539b4a9a8603a8feb5cae78c#L313

The command do to this is `rhub::check(platform = "solaris-x86-patched-ods")`

**Comment by eddelbuettel** [comment] 2021-04-26 14:38
I see.  CRAN is famously non-communicative about this but _I think_ I recall them not actually testing all of CRAN with the non-gcc compiler.  I could be wrong.

In any event, exceptions can be difficult, and if you check the Rcpp mailing list and old issues here you will find numerous discussions about the problems with `longjmp` across compilation units and shared libraries.  Maybe it just won't work with ODS. I really do not know.  As as I have (sorry to be blunt) zero incentive to work on this, I can only guide if you wanted to attempt this.  It may well be a dead end.  Sorry!   (With that, allow me to repeat the earlier question:  can you simply _avoid_ the call to `stop()`?)

**Comment by dbaston** [comment] 2021-04-26 15:08
>  I recall them not actually testing all of CRAN with the non-gcc compiler. I could be wrong.

I don't know the scope of what they're testing. They've advised me to fix the error in order to retain my package on CRAN.

> As as I have (sorry to be blunt) zero incentive to work on this

No apology needed -- I don't fault you in the least for not wanting to diagnose a segfault on a 32-bit build with an obscure proprietary compiler on an old version of an operating system most of us haven't thought about in 20 years.

> can you simply avoid the call to stop()

Yes, I can wrap all of my functions in a try/catch and convert the `stop` calls to `Rf_error`. Or do an OS check and skip the tests on Solaris.

**Comment by eddelbuettel** [comment] 2021-04-26 15:18
> skip the tests on Solaris.

I have done that, and stand by it.  As you say, the OS is of help in finding issues, but also has an ability to get in the way. Here you appear to be close to a "fix" for the CRAN issue that takes you one line in a test script.  I have no reservations doing that in my packages.

**Comment by dbaston** [comment] 2021-04-26 16:15
Maybe it's not the best solution, but I ended up with this. I was already wrapping functions in a try/catch to convert various C++ exceptions into the Rcpp exception type, so it wasn't a big change.

```
Rcpp::NumericVector myFunction() {
  try {
    // do stuff   
  } catch (std::exception & e) {
    // throw predictable exception class
#ifdef __SUNPRO_CC
    Rf_error(e.what());
    return R_NilValue;
#else
    Rcpp::stop(e.what());
#endif
  }
}
```

**Comment by kevinushey** [comment] 2021-04-26 16:27
> Thanks for looking into this. As I mentioned, the Solaris gcc builds are OK; the problem only shows up when the Oracle compiler is used (as is the case on CRAN).

FWIW, my understanding is that Rcpp and all its dependencies use gcc on CRAN's Solaris check machine. Can you share your package + the actual errors you're seeing on CRAN?

**Comment by dbaston** [comment] 2021-04-26 16:38
> Can you share your package

Package is: https://github.com/isciences/exactextractr

CRAN error, as emailed to me, is:

> On Solaris it installs but segfaults at
> 
>  > test_check("exactextractr")
> 
>   *** caught segfault ***
> address 0, cause 'memory not mapped'
> 
> Traceback:
>   1: CPP_stats(x, weights, wkb, default_value, default_weight,
> coverage_area,     area_method, fun, max_cells_in_memory, quantiles)
>   2: FUN(X[[i]], ...)
>   3: lapply(X = X, FUN = FUN, ...)
>   4: sapply(sf::st_as_binary(geoms, EWKB = TRUE), function(wkb) {    ret
> <- CPP_stats(x, weights, wkb, default_value, default_weight,
> coverage_area, area_method, fun, max_cells_in_memory,         quantiles)
>     update_progress()    return(ret)})
> 
> Please fix and resubmit.

**Comment by dbaston** [comment] 2021-04-26 16:44
But you're right, https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-patched-solaris-x86 suggests that CRAN should be using g++ for packages linking to Rcpp. Will contact them and see if I can get an answer.

**Comment by eddelbuettel** [comment] 2021-04-26 17:10
Re your code snippet:

- as you may know, any function using ` [[Rcpp::export]]` already gets a `try/catch` block by default
- replacing `Rcpp::stop()` with `Rf_errror()` is an interesting approach and may give us a hint because ... we really do not do much more -- maybe you can keep digging there and see what tickles the odd behaviour?

**Comment by dbaston** [comment] 2021-04-29 01:07
Digging slowly, since I'm unfamiliar with both the Rcpp internals and the Oracle tools. Here's a stack trace:

```
t@1 (l@1) signal SEGV (no mapping at the fault address) in _memcpy at 0xfe4f5e3f
0xfe4f5e3f: _memcpy+0x00ff:     repz movsb
Current function is std::char_traits<char>::copy
dbx: warning: can't find file "/home/dam/mgar/pkg/gcc5/trunk/work/solaris10-i386/build-isa-pentium_pro/objdir/i386-pc-solaris2.10/libstdc++-v3/include/bits/char_traits.h"
(dbx) where
current thread: t@1
  [1] _memcpy(0x8044e28, 0xfcd5393b, 0xae44538, 0x0, 0xa8fb000, 0x0), at 0xfe4f5e3f
=>[2] std::char_traits<char>::copy() (inlined), line 290 in "char_traits.h"
  [3] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy() (inlined), line 299 in "char_traits.h"
  [4] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(this = 0x8044e28, __str = CLASS), line 272 in "char_traits.h"
  [5] demangle(0x8044e28, 0x8044e2c, 0x8044e08, 0xfcdb5e28, 0xfd190387, 0xa8fb060, 0x8044dc0, 0xfd1a04f4, 0xfd190387, 0xfd190398, 0x8044e30, 0xa8fb060, 0x8044e2c, 0xfd1a04f4, 0x8044e58, 0xfd18b7d0, 0x8044e28, 0x8044e2c, 0x8044e30, 0xfd474333), at 0xfd47460f
  [6] demangle(0x8044e28, 0x8044e2c, 0x8044e30, 0xfd474333, 0xfd474319, 0xfd1a04f4, 0x8044e00, 0xfcd7031e, 0xfcd70309, 0xfd1a04f4, 0xae44538, 0x0, 0xa8fb000, 0xfd1a04f4, 0x8044e20, 0x0, 0x84f59b8, 0xfd4c2e28, 0xfcd7001b, 0xa8fb040), at 0xfd18bfc9
  [7] exception_to_condition_template<Rcpp::exception>(0xa8fb060, 0x1, 0x8044e88, 0xfeaf40ae, 0x8044e60, 0xfd1a04f4), at 0xfd18b7d0
  [8] sourceCpp_1_doIt(0xab9b9b0, 0x8045428, 0x8045418, 0x811df1b, 0xfd189e90, 0x0), at 0xfd18a19e
  [9] R_doDotCall(0xfd189e90, 0x0, 0x80452f0, 0xab872d0), at 0x811d518
  [10] do_dotcall(0xab872d0, 0x88b6068, 0xab9b9b0, 0xab9ba10), at 0x811df1b
  [11] Rf_eval(0xab872d0, 0xab9ba10, 0x8045738, 0x814abda), at 0x815e160
  [12] Rf_evalList(0xab934c0, 0xab9ba10, 0xab934a0, 0x0), at 0x81638ec
  [13] Rf_eval(0xab934a0, 0xab9ba10, 0xab94f50, 0x815e02d), at 0x815e0b8
  [14] R_execClosure(0xab9baf0, 0xab9ba10, 0x88c4c80, 0x88c4c80, 0x84f59b8, 0xab94f50, 0x88c4c80, 0x8164175), at 0x81601b0
  [15] Rf_applyClosure(0xab9baf0, 0xab94f50, 0x84f59b8, 0x88c4c80, 0x84f59b8, 0x88c4c80, 0xab9baf0, 0x1), at 0x815fd60
  [16] Rf_eval(0xab9baf0, 0x88c4c80, 0x8046028, 0x81ab5db), at 0x815e02d
  [17] Rf_ReplIteration(0x88c4c80, 0x0, 0x0, 0x8046040), at 0x81ab606
  [18] R_ReplConsole(0x88c4c80, 0x0, 0x0, 0x80471d4), at 0x81ab7bf
  [19] run_Rmainloop(0x80470a4, 0x80471d4, 0x80470dc, 0x806c9f2, 0x1, 0x80470e8), at 0x81aceac
  [20] main(0x1, 0x80470e8, 0x80470f0), at 0x806cb83
```

**Comment by Enchufa2** [comment] 2021-04-29 08:35
[Anyone with an Oracle support account](https://support.oracle.com/knowledge/Sun%20Microsystems/2083262_1.html)? :-\

**Comment by eddelbuettel** [comment] 2022-01-01 17:02
As the Solaris machine was quietly retired from the CRAN tests I am closing this.

**Closed by eddelbuettel** 2022-01-01 17:02 UTC
