### ISSUE TITLE
enterRNGScope gets fooled by interuption

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#241] opened 2015-01-30 09:01 UTC
See http://stackoverflow.com/questions/28227971/whats-causing-this-strange-random-number-generator-behaviour/28232296#28232296 and hadley/plyr#229

Interuption fools the business of `enterRNGscope` and `exitRNGScope`. 

One possible workaround would be for `enterRNGScope` to look up the R frames and identify `Rcpp` function depth, rather than relying on a global setting like `RNGScopeCounter`.

**Comment by eddelbuettel** [comment] 2015-01-30 12:57
I saw the SO post yesterday and shrugged; this is pretty much user error to me.  The RNG also fails when you pull the power cable ....

**Comment by romainfrancois** [comment] 2015-01-30 12:59
Ok. Then there's no point for me to investigate and solve this.

**Comment by eddelbuettel** [comment] 2015-01-30 13:04
That's not what I said.

**Comment by eddelbuettel** [comment] 2015-01-30 13:10
If you really think this is a design issue (in either dplyr or Rcpp)  that could be addressed by a different design, _of course_ I would be curious to see it.  

But otherwise it may join dozens of other open issue tickets; and I don't think I rank this one near the top in terms of importance.  It is of "probably nice to have fixed eventually" quality to me, and there are countless other things that could be fixed or improved as well.   Some I may consider more important.  That was all.

**Comment by romainfrancois** [comment] 2015-01-30 13:29
This is clearly an Rcpp design error. Interruption over a function generated by attributes will lead to `exitRNGScope` not being called, so the `RNGScopeCounter` will stay too high forever, so `PutRNGstate ` is never called, so the whole thing is broken. 

I'll fix it in Rcpp11 and Rcpp14, so you'll be able to satisfy your curiosity from this implementation.

**Comment by eddelbuettel** [comment] 2015-01-30 13:53
Sounds good, and if you feel like carrying it over we'll definitely look at it.  

The dplyr-using gentleman asking on SO won't otherwise have much until dplyr switches to Rcpp11 ...

**Comment by romainfrancois** [comment] 2015-01-30 13:59
FWIW, it was "plyr", not "dplyr".

**Comment by eddelbuettel** [comment] 2015-01-30 14:09
Thanks for the correction.

**Comment by jjallaire** [comment] 2015-01-30 15:15
Just want to be sure I understand the issue in detail. From my reading of the VOID_END_RCPP macro the call to Rf_onintr() should be occurring after exiting from the try scope (and therefore after the RNGScope destructor has executed). I can't see an obvious way that RNGScope doesn't work as expected here but I'm almost certainly missing something.

**Comment by romainfrancois** [comment] 2015-01-30 15:29
Here is it for reference: 

```
#define VOID_END_RCPP                                                          \
  }                                                                            \
  catch (Rcpp::internal::InterruptedException &__ex__) {                       \
    Rf_onintr();                                                               \
  }                                                                            \
  catch (std::exception &__ex__) {                                             \
    forward_exception_to_r(__ex__);                                            \
  }                                                                            \
  catch (...) {                                                                \
    ::Rf_error("c++ exception (unknown reason)");                              \
  }
```

So `Rf_onintr` is only called when there was a `Rcpp:: checkUserInterrupt()` catching the interrupt, throwing a custom expression so that the stack gets unwound properly, ... I don't think that it is the case here. `VOID_END_RCPP` does not catch raw jumps, it can only catch the sentinel thing that was thrown when an interrupt was detected in the C++ code through `checkUserInterrupt`

The interrupt is caught by `Sys.sleep`, ie. by an R function called from `Rcpp` and `loop_apply` is being jumped over. 

There is no way to avoid greedy jumps, but then it leaves us with a wrong value for `RNGScopeCounter` for the next time it is used. Perhaps there could be a check that sets it to `0` when entering the highest attributes powered function in the call stack.

**Comment by jjallaire** [comment] 2015-01-30 15:31
Interesting! Where is the raw jump coming from? (presumably the R code
called via "Function f" ?)

**Comment by pitakakariki** [comment] 2015-01-30 19:58
I don't think this is user error. I can see how it looks that way in the SO question, where I'm deliberately interrupting llply to make the bug reproducible. But in the wild the interruption might have happened days ago.

The use case I'm worried about:
  1. I'm testing a simulation experiment. I've used set.seed so I can reproduce any non-deterministic errors.
  2. Watching the diagnostic messages I'm printing, I notice something isn't working so I interrupt the process.
  3. I try to fix the bug and run the test again with the same seed.

At the moment I'll need to restart my R session before I can trust step 3.

**Comment by eddelbuettel** [comment] 2015-01-30 20:05
Which is why some of us work on the command-line where sessions start fresh.   Or use command-line programs launched in cluster setups common for scientific computing etc pp.  The common mode for these undertakings is "batch".

And with fixed seeds, you get predictable behaviour.  

You may well desire to have different behaviour, but that still won't make it that likely that we as volunteers code to your spec.  As I mentioned, it seems to fix the use case of a larger number of users. 

(Well-designed) patches are of course welcome.  What you hit upon is not a trivial problem, and a change may risk affecting a large number of users currently not having an issue to the benefit of just you.

**Comment by pitakakariki** [comment] 2015-01-30 20:22
I didn't mean to demand your time fixing this, I just wanted to make sure you understood why it's a bug. I did use a fresh session as a workaround, but then I went back and spent most of yesterday trying to find a way to reliably reproduce the bug.

**Comment by eddelbuettel** [comment] 2015-01-30 20:24
I think it is simply outside of the scope. We made no promises that it would support _random_ user interaction.  If you think you must restore RNGstate, why don't you fetch and serialize it before your job, and then restore it?

**Comment by pitakakariki** [comment] 2015-01-30 20:39
I wonder if a wrapper function would work as a workaround.

    setSeed <- function(seed) {

        resetRcppRNG()
        set.seed(seed)
    }

I'm guessing this would get messy if someone starts playing Inception with R calling Rcpp calling R calling Rcpp, but that's probably even less common than my use case?

**Comment by eddelbuettel** [comment] 2015-01-30 20:55
I think this starts to the right direction.  But from my reading of `GetRNGstate()` and `PutRNGstate()` in _Writing R Extensions_, these are deliberately opaque.  

So you coud either go in and rewrite them with storage in some other state-keeping object.

Or you could equally well switch to a different RNG altogether.  Boost and the C++11 standard offer quite a choice; my RcppZiggurat package has a simple and fast one etc pp

**Comment by pitakakariki** [comment] 2015-01-30 21:12
The RNG is happening in someone else's package though, I was calling `exactRLRT` from RLRsim which depends on Rcpp.

So I guess I need a way to repair Rcpp's RNG scope. I assume that's not as simple as setting `RNGScopeCounter` to zero?

**Comment by eddelbuettel** [comment] 2015-01-30 21:19
Ultimately we just call `GetRNGstate()` and `PutRNGstate()`.  The `RNGScopeCounter` is just a toggle to know if/when we need to reset.   You could experiment with overriding its value if you're sure you are done at C++.

**Comment by jjallaire** [comment] 2015-01-30 21:35
The core problem here IMHO is the interaction between GetRNGstate and
PutRNGstate and the execution of arbitrary R code via the "Function f"
parameter. The Get/Put RNG functions in R are intended to be used at the
top level and carry with them an implicit assertion that Get/Put won't be
called again within the scope of the top level Get/Put. This is why we use
a counter (so that multiple layers of Rcpp code can use RNGScope without
explicit coordination). As soon as we introduce the calling of arbitrary R
code via the "Function f" parameter all bets are off! Note that if the
arbitrary R code uses Rcpp it will use the same counter and be fine but if
it calls standard C Get/Put RNG state it won't be coordinated and the
results you are seeing will be expected.

I think we've done what we reasonably can on the Rcpp side (all Rcpp code
is coordinated). Since there isn't a general mechanism for R C API code to
coordinate this I don't think it's possible to solve this in a general
fashion.


On Fri, Jan 30, 2015 at 4:19 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment] 2015-01-30 21:42
Well put, and I agree.

**Comment by pitakakariki** [comment] 2015-01-30 22:11
In this case though Get/Put aren't being called in R code. "Function f" is just `Sys.sleep`! I suspect the more general case could only be solved if R-Core were willing to have nesting Get/Put calls. 

Meanwhile, this seems to work as a stopgap measure.

    #include <Rcpp.h>
    using namespace Rcpp;

    // [[Rcpp::export]]
    void resetRcppRNG() {

        unsigned long i = internal::enterRNGScope();

        while(i > 0) i = internal::exitRNGScope();

        return;
    }

**Comment by pitakakariki** [comment] 2015-01-31 05:11
I'm pretty certain that `Function__operator.h` is the wrong place to do this, but is there anything stopping us from simply fencing off the R callback like this?

	template <typename T1>
	SEXP operator()(const T1& t1) const {

		internal::exitRNGScope() ;
		SEXP temp = Rcpp_eval( Rcpp_lcons( Storage::get__(), pairlist(t1) ) ) ;
		internal::enterRNGScope() ;
		
		return temp ;
	}

I've tested this and it fixes this particular bug, can't promise it doesn't introduce new ones though.

**Comment by romainfrancois** [comment] 2015-01-31 10:23
Not sure this would fix it, and break the initial intent. IMO the place to fix it is in the code generated by attributes.

**Comment by pitakakariki** [comment] 2015-01-31 10:43
I've tried my code above, and it does stop this issue from happening. This way code in between the fence posts should be able to get/put rng state safely too.

**Comment by jjallaire** [comment] 2015-01-31 11:13
I don't think we want to be monkeying with RNG scopes here. Honestly,
this "bug" is more like a known failure mode at the hairy edge of the
mechanics required to weave R, C, and C++ together. Attempting to
apply targeted fixes at making the failure mode go away are likely to
introduce others.

All of that said, there may be a deeper issue here worth exploring.
The fact that longjmp can escape from a call back into R means that
all destructors will be bypassed (not just the RNG ones).
@romainfrancois, looking at the innermost Rcpp_evel code here:

https://github.com/RcppCore/Rcpp/blob/3ef9e662d89ebcfe71734675071568302bf10104/inst/include/Rcpp/api/meat/Rcpp_eval.h#L35-L39

It looks like we wrap the call in tryCatch. I guess tryCatch only
masks error long jumps not interruption ones?

I can think of one solution to this, which would be to wrap our
invocation of the R function within R_ToplevelExec. Granted, this
could violate the principle above of monkeying with the seams of R, C,
and C++ but this one seems like a really fundamental issue which we
don't have right. Can you think of a reason not to explore this
avenue?

**Comment by jjallaire** [comment] 2015-01-31 11:57
I've put up a PR for discussion that wraps Rcpp_eval in R_ToplevelExec: https://github.com/RcppCore/Rcpp/pull/244. Obviously a change like this bears a lot of discussion, scrutiny, and testing.

**Comment by eddelbuettel** [comment] 2015-01-31 13:47
Wow. That is pretty promising work and indeed a cleanup -- thanks so much.

Batch test against 326 revdeps launched...

**Comment by eddelbuettel** [comment] 2015-01-31 21:22
Looks pretty good:

```{bash}
edd@max:~/git/rcpp-logs/results(master)$ ./Rcpp-Summary-20150131.R
Good          319 
  AsIs        318 
  w/Patches   1 
Bad           7 
  Unclear     2 
  NotRcpp     5 
Skipped       2 
Total         328 
Bad Percent   0.00613497 
edd@max:~/git/rcpp-logs/results(master)$ 
```

Two need failures in their respective regression  tests: `dplyr` (and I told Hadley) and `scrm` which I know little about at this point.

**Comment by jjallaire** [comment] 2015-02-01 02:08
Could you tell whether the failures had anything to do with this change?
(seem hard to believe they would). When I run R CMD check on dplyr locally
(against the PR branch) I get this:

 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  } no warnings given

  4. Failure(@test-joins.r#357): joins between factor and character coerces
to character with a warning (#684)
  {
      res <- inner_join(d2, d1)
  } no warnings given

  5. Error: no utf8 invasion (#722)
----------------------------------------------
  could not find function "skip_on_cran"

Which doesn't seem related but I guess you never really know until you turn
over all the leaves....

On Sat, Jan 31, 2015 at 4:22 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment] 2015-02-01 02:18
I don't know.  With `scrm` is similarly mysterious:

```
* checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  scrm("2 1 -I 2 1 1 1.0") no warnings given
  
  Error: Test failures
  In addition: Warning messages:
  1: In eval(substitute(expr), envir, enclos) :
    Ignoring Seed argument. Set a seed in R.
  2: In eval(substitute(expr), envir, enclos) :
    Ignoring Seed argument. Set a seed in R.
  3: In eval(substitute(expr), envir, enclos) :
    No summary statisics specified. No output will be produced.
  4: In eval(substitute(expr), envir, enclos) :
    No summary statisics specified. No output will be produced.
  Execution halted
```
I'd say that does not look like us, but one could backtrack and try Rcpp 0.11.4 ...

**Comment by eddelbuettel** [comment] 2015-02-01 02:19
We could at least page @hadley regarding the `dplyr` issue...

**Comment by jjallaire** [comment] 2015-02-01 02:35
I tested with Rcpp 0.11.4 and Rcpp moaster and *this change* specifically
causes the following tests to fail:

1. Failure(@test-joins.r#340): joins coerce factors with different levels
to character (#684)
{
    res <- inner_join(d1, d2)
} no warnings given

2. Failure(@test-joins.r#346): joins coerce factors with different levels
to character (#684)
{
    res <- inner_join(d1, d2)
} no warnings given

3. Failure(@test-joins.r#354): joins between factor and character coerces
to character with a warning (#684)
{
    res <- inner_join(d1, d2)
} no warnings given

4. Failure(@test-joins.r#357): joins between factor and character coerces
to character with a warning (#684)
{
    res <- inner_join(d2, d1)
} no warnings given

@hadley this is a change that closes off a case whereby when executing R
functions from within Rcpp if an interrupt occurred then it would bypass
all destructors on the stack. With this change we execute the R function
within an R_toplevelExec block so that the longjmp and destructor bypass
doesn't occur. Not sure how this might interact with the test_joins.r
tests....


On Sat, Jan 31, 2015 at 9:18 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by jjallaire** [comment] 2015-02-01 02:48
I see where the test is failing and have some inkling about how it could be interacting with this code but I'm not sure it's a problem. The test that fails is checking whether a warning occurs or not. If you execute the following code against the PR branch you'll see that if you just execute the first block you DO get a warning. Then if you execute the second block you get a test failing for expect_warning but then the warning occurs once again (even though the test said that it didn't):

```r
library(testthat)

d1 <- data_frame( a = factor( c("a", "b", "c" ) ) )
d2 <- data_frame( a = factor( c("a", "e" ) ) )
res <- inner_join( d1, d2 )

d1 <- data_frame( a = factor( c("a", "b", "c" ) ) )
d2 <- data_frame( a = factor( c("a", "e" ) ) )
expect_warning( { res <- inner_join( d1, d2 ) })
```

My best guess is that inner_join calls C++ code which in turn executes some R code which we expect to be yielding a warning. The warning happens but the new mechanism somehow changes the timing/ordering of when that warning is actually registered by R such that the test fails. Perhaps this is an acceptable change or perhaps we need to be doing something else to force warning to be reported, I'm not sure.

**Comment by romainfrancois** [comment] 2015-02-01 12:10
I'll have a look next week.

**Comment by jjallaire** [comment] 2015-02-01 17:58
Looking at the the code for test_that::expect_warning there is business
related to restart contexts, etc. Since the R_toplevelExec creates a new
top level context this might be running askance of what expect_warning
typically sees and causing the test to fail.

I don't however think this is an actual failure as the warnings clearly are
occurring just somehow missed by expect_warning. Obviously this bears
closer scrutiny but that's my take so far, let me know what you think once
you've had time to dig into it.

**Comment by romainfrancois** [comment] 2015-02-02 11:38
Untangling this from `dplyr`. The issue is that we call the `warning` function. Consider this: 

```
#include <Rcpp.h>
using namespace Rcpp ;

// [[Rcpp::export]]
int foo(){
  Function warning("warning") ;
  warning( "foo", _["call."] = false ) ;
  return 3 ;
}    

/*** R
    res <- tryCatch( foo(), warning = function(w){
        message("warning")
    })
    print(res)
*/
```

I get: 

```
> require(Rcpp)
Le chargement a nécessité le package : Rcpp
> sourceCpp( "/tmp/warning.cpp" )

>     res <- tryCatch( foo(), warning = function(w){
+         message("warning")
+     })

>     print(res)
[1] 3
Message d'avis :
foo
```

The warning gets printed because it reaches the top level context you set up, so there is no chance to catch it. 

So if you go along with top level exec, etc ... you need to find a way to handle those warnings. Perhaps `options( warning.expression = )`. 

The somewhat good news is that we do not need to call back to R to issue a warning. we can just use `Rf_warning`, i.e. this seems correct. 

```
#include <Rcpp.h>
using namespace Rcpp ;
 
// [[Rcpp::export]]
int foo(){
  Rf_warning( "foo" ) ;
  return 3 ;
}    
         
/*** R 
    options( "warn" = 1 )
    res <- tryCatch( foo(), warning = function(w){
        message("warning")
    })       
    res
*/
```

giving:

```
$ RcppScript /tmp/warning.cpp

> options(warn = 1)

> res <- tryCatch(foo(), warning = function(w) {
+     message("warning")
+ })
warning

> res
NULL
```

**Comment by jjallaire** [comment] 2015-02-02 12:12
Interesting! Impressive detective work :-)

In the dplyr test case it does seem like the warnings ultimately propagate
as they do print to the console. So I'm assuming they are not "eaten" by
R_toplevelExec but that they occur in some different sequence. Is that
correct?

2 questions:

(1) Do you recommend that we modify the Rcpp_eval code in some way to
account for this or is there nothing we can safely and generally do at that
level? (i.e. should Rcpp_eval also be catching and forwarding warnings or
is this already taken care of via some other mechanism)

(2) Is the solution for dplyr to just call Rf_warning rather than the R
warning function? There is one other package that failed the test suite and
if they've got the same issue I'll recommend whatever change you suggest
here.

**Comment by romainfrancois** [comment] 2015-02-02 12:20
I'm testing `dplyr` now and it should call `Rf_warning` anyway. The only reason we used a call back to `warning` R function is because I did not know about `Rf_warning`. 

warnings are not eaten indeed, but they are not catchable. 

For 1) `Rcpp_eval` could be modified I guess to act on warnings the same way it deals with errors. This would need modifying the call to `tryCatch` here. https://github.com/RcppCore/Rcpp/blob/3ef9e662d89ebcfe71734675071568302bf10104/inst/include/Rcpp/api/meat/Rcpp_eval.h#L35

So that there is a `warning = .rcpp_warning_recorder` or something. And then if a warning was indeed issued, it could be rethrown using `Rf_warning`. Maybe this would work.

**Comment by romainfrancois** [comment] 2015-02-02 14:24
So dplyr seems to travis test fine against the bugfix/eval-interruption branch. I guess it makes it more stable to issue warnings with `Rf_warning` than through a call back to the R `warning` function

**Comment by jjallaire** [comment] 2015-02-02 15:02
Okay, that's fantastic! Much appreciated.

Do you think I should pursue the .rcpp_warning_recorder avenue you alluded
to? It does seem like it would make the implementation more "complete"
however that would be mucking around in some pretty core/sensitive Rcpp
internals so I'm not sure if the gain is worth it. Let me know what you
think...

**Comment by romainfrancois** [comment] 2015-02-02 15:09
Actually `tryCatch` is too strong, you'd rather need a `withCallingHandlers` to catch warnings. See: 

```
> f <- function(){ print("before"); warning("some warning"); print("after") }
> tryCatch( f(), warning = function(w){ message( "warning caught") } )
[1] "before"
warning caught
> withCallingHandlers( f(), warning = function(w){ message( "warning acknowledged") } )
[1] "before"
warning acknowledged
[1] "after"
Message d'avis :
In f() : some warning
```

So perhaps something like `withCallingHandlers( tryCatch( expr, error = .rcpp_error_recorder ), warning = .rcpp_warning_recorder )` or something like that.

**Comment by jjallaire** [comment] 2015-02-02 15:15
Okay, that makes perfect sense.

**Comment by jjallaire** [comment] 2015-02-02 15:34
I checked on the scrm package and it's the same issue as Romain identified in dplyr (issuing a warning through R rather than Rf_warning). I tried changing both usages in the package to avail themselves of Rf_warning and the tests pass. I'll send them a PR.

We have a bit of a decision to make here. I don't think it's an unacceptable state of affairs in Rcpp code to say that you need to use Rf_warning rather than calling back into base::warning. To that extent we could make the required changes to dplyr and scrm and move on. 

Alternatively, Romain has outlined a way for us to modify Rcpp_eval to actually catch and forward the warnings. This change would make our implementation more complete and close off the Rf_warning loophole however I do have some concern that we could easily manage to break something else doing it.

**Comment by romainfrancois** [comment] 2015-02-02 15:36
I do think both are needed if trapping calls to R in a top level context: 

 - when C++ code wants to issue a warning, you can just use `R_warning` or perhaps come up with an `Rcpp::warning` 
 - when an R function called from C++ warns.

**Comment by jjallaire** [comment] 2015-02-02 15:42
Okay, I'll explore moving to withCallingHandlers

**Comment by jjallaire** [comment] 2015-02-02 18:20
I've updated the PR to use withCallingHandlers to catch warnings as well. Does this implementation look okay to you? (and hidden surprises I might not be considering). With these changes both the dplyr and scrm tests that formerly failed due to warnings not being handled now pass.

**Comment by hadley** [comment] 2015-02-03 02:19
Haven't followed the complete discussion, but might be worth also testing with `options(warn=2)` which turns warnings into errors?

**Comment by romainfrancois** [comment] 2015-02-03 08:40
I guess if the `tryCatch` call is the most nested than it should be fine. @jjallaire if I did it right `dplyr` runs against the branch you created on travis, so you might be able to relaunch travis testing of `dplyr`.

**Comment by jjallaire** [comment] 2015-02-03 11:30
Thanks, I've re-run the dplyr tests and all looks well.

**Comment by eddelbuettel** [comment] 2015-02-03 12:32
I also ran a full suite overnight and the result is the best yet:

```{.bash}
edd@max:~/git/rcpp-logs/results(master)$ ./Rcpp-Summary-20150203.R
Good          322 
  AsIs        322 
  w/Patches   0 
Bad           6 
  Unclear     1 
  NotRcpp     5 
Skipped       2 
Total         330 
Bad Percent   0.00304878 
edd@max:~/git/rcpp-logs/results(master)$ 
```

The five known failures are unchanged, that is not us (see [rcpp-logs repo for details](https://github.com/RcppCore/rcpp-logs)) and the 'unclear' one was a (temp. ?) failure in the otherwise stable/standard `rARPACK` package on some linking with a numeric routine which was already irreproducible in a re-run.

So thanks for this -- very nice work.  I'll fold the PR in.

**Closed** 2015-02-03 12:45 UTC

**Comment by jjallaire** [comment] 2015-02-03 13:47
Indeed, very glad we sorted this all out and managed to get the right change!

**Comment by eddelbuettel** [comment] 2015-02-03 13:48
A big thanks to you, @kevinushey and @romainfrancois.
