### ISSUE TITLE
string_proxy doesn't play nicely with std::string

### ISSUE THREAD

**Issue by dcdillon** [RcppCore/Rcpp#385] opened 2015-10-22 15:37 UTC
The following code does NOT compile and probably should given that the second example does compile.

``` c++
// [[Rcpp::export]]
std::vector< std::string > get_unique(Rcpp::CharacterMatrix m)
{
  std::set< std::string > unique;

  for (int32_t i = 0; i < m.nrow(); ++i)
  {
    Rcpp::CharacterMatrix::Row row = m.row(i);

    for (int32_t j= 0; j < m.ncol(); ++j)
    {
      unique.insert(row[j]); // doesn't work
    }
  }

  std::vector< std::string > retval;
  retval.insert(retval.begin(), unique.begin(), unique.end());
  return retval;
}
```

This does compile

``` c++
// [[Rcpp::export]]
std::vector< std::string > get_unique(Rcpp::CharacterMatrix m)
{
  std::set< std::string > unique;

  for (int32_t i = 0; i < m.nrow(); ++i)
  {
    Rcpp::CharacterMatrix::Row row = m.row(i);

    for (int32_t j= 0; j < m.ncol(); ++j)
    {
      Rcpp::String str(row[j]);
      unique.insert(str); // this works
    }
  }

  std::vector< std::string > retval;
  retval.insert(retval.begin(), unique.begin(), unique.end());
  return retval;
}
```

**Comment by thirdwing** [comment] 2015-10-22 16:34
I think this can be fixed by adding something like:

```
operator std::string() const {
    const char* st = CHAR(get()) ;
    return std::string( st, st+strlen(st) ) ;
}
```

in `string_proxy.h`.

But I don't know why we comment the `wstring` part: https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/string_proxy.h#L122-L125

**Comment by eddelbuettel** [comment] 2015-10-22 17:13
As I recall, `wstring` and friends were one looked at in order to get to utf-8 etc.  That early attempt never completed and the commented-out line may be a leftover from it.

**Comment by thirdwing** [comment] 2015-10-22 18:48
I just have a try, adding a function might cause many problems.

@dcdillon I also think what you have met is expected behavior due to  https://github.com/RcppCore/Rcpp/blob/master/src/attributes.cpp#L3227-L3230

**Comment by dcdillon** [comment] 2015-10-22 20:14
Did you try adding an `operator const char *() const`?  That *might* be sufficient.  I, unfortunately, don't have a development environment set up for Rcpp here at work so I can't test it myself right now.

**Comment by dcdillon** [comment] 2015-11-08 14:03
I poked around this issue some more this morning and adding an `operator std::string()` to `string_proxy` causes a bunch of ambiguous overload errors.  Each one of these can be gotten around by making them more explicit, but I would suspect that in client code, the same ambiguities would present themselves meaning that changing this would be VERY painful.

**Comment by thirdwing** [comment] 2015-11-08 15:06
I know exactly what you mean here. And I think it might not be worth doing.

**Comment by dcdillon** [comment] 2015-11-08 16:53
Given all that, I think we should either close this (for cleanliness) or give it a tag like "Wishlist".

**Closed** 2021-01-23 02:53 UTC
Labels: no-issue-activity, wishlist, wontfix
