### ISSUE TITLE
match() cares too much about the declared encoding

### ISSUE THREAD

**Issue by krlmlr** [RcppCore/Rcpp#489] opened 2016-06-04 20:27 UTC
```
encoded <- function(x) {
  Encoding(x) <- "UTF-8"
  x
}

unencoded <- function(x) {
  Encoding(x) <- "unknown"
  x
}

f <- Rcpp::cppFunction('
  IntegerVector call_match(CharacterVector x, CharacterVector y) {
    return Rcpp::match(x, y); }')

f(encoded("ä"), unencoded("ä"))
## [1] NA
```

This is different from how R handles things:

```
match(encoded("ä"), unencoded("ä"))
## [1] 1
```

I wonder if Rcpp's behavior is by design, or simply unspecified in this particular case. I think this is the reason behind https://github.com/hadley/dplyr/issues/1885.

Very likely a duplicate of https://github.com/RcppCore/Rcpp/issues/189, but I'm not sure.

**Comment by thirdwing** [comment] 2016-06-05 02:26
Encoding problem again. I don't think this is by design.

Maybe we need to find a better method to handle the string encoding.

**Comment by eddelbuettel** [comment] 2016-06-05 04:53
This is a _really hard problem_ which AFAFIK the dplyr guys have wrestled with extensively.

I do not think this is addressable is a quick local patch. We tried once or twice and had to backtrack because of unitended consequences.  And yes, it looks like a duplicate of #189 so we should just close (or merge if one can) this.

**Comment by kevinushey** [comment] 2016-06-06 04:46
FWIW, Rcpp `match` implementation is basically derived from [fastmatch](https://cran.r-project.org/web/packages/fastmatch/index.html), which does not handle encoding differences either:

```
library(fastmatch)

encoded <- function(x) {
  Encoding(x) <- "UTF-8"
  x
}

unencoded <- function(x) {
  Encoding(x) <- "unknown"
  x
}

fmatch(encoded("ä"), unencoded("ä"))
```

which also prints

```
> fmatch(encoded("ä"), unencoded("ä"))
[1] NA
```

I haven't peeked at the sources yet, but I wouldn't be surprised if strings were being compared differently here.

**Comment by hadley** [comment] 2016-06-08 19:19
Here's a link to source code for `match5()`, which is what `match()` eventually calls: https://github.com/wch/r-source/blob/d0b19e36e5fb1d7d5f275077c3e987b89eb954aa/src/main/unique.c#L974

Looks like about half the code is for dealing with varying encodings

**Comment by eddelbuettel** [comment] 2016-06-08 19:21
If only more of these functions were actually proving an API would could call...

**Comment by krlmlr** [comment] 2016-06-14 13:06
Would it be easier to make sure that encoding *always* matters for Rcpp strings?

**Comment by eddelbuettel** [comment] 2016-06-14 14:14
I don't know.  I am not too unhappy with the status quo and we have _a lot_ of dependent packages now.

Maybe a complete parallel set of functions may work, but it would be a lot of work. PRs welcome.  My gut feel is that this would be more than a small job (of, say, Google Summer of Code scale).

**Closed** 2021-01-23 02:53 UTC
Labels: encoding, no-issue-activity
