### ISSUE TITLE
rcpp name export error when installing packages that depend on rcpp

### ISSUE THREAD

**Issue by alejandrohagan** [RcppCore/Rcpp#1262] opened 2023-03-31 04:37 UTC
]hi!

I think (hopefully) did all the instructions articulated in how to make a new issue. Please see below for my session info:

## description of problem

When I go to install the "forecast" package (`install.packages("forecast",dependencies = TRUE)`, I get an error code that appears to reference some name export issue related to Rcpp (see read out of error code below). 

I checked [posit package manager](https://packagemanager.rstudio.com/client/#/repos/2/packages/Rcpp) for more information on required dependencies for the rcpp package but didn't see any (Ubuntu 22.04 Jammy)

## Session Info
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2   

## Installation Error in R

In file included from calcBATS.cpp:1:
calcBATS.h:38:1: error: ‘RcppExport’ does not name a type
   38 | RcppExport SEXP calcBATS(SEXP ys, SEXP yHats, SEXP wTransposes, SEXP Fs, SEXP xs, SEXP gs, SEXP es ) ;
      | ^~~~~~~~~~
calcBATS.h:40:1: error: ‘RcppExport’ does not name a type
   40 | RcppExport SEXP calcBATSFaster(SEXP ys, SEXP yHats, SEXP wTransposes, SEXP Fs, SEXP xs, SEXP gs, SEXP es, SEXP xNought_s, SEXP sPeriods_s, SEXP betaV, SEXP tau_s, SEXP p_s, SEXP q_s )  ;
      | ^~~~~~~~~~
In file included from calcBATS.cpp:1:
calcBATS.h:42:1: error: ‘RcppExport’ does not name a type
   42 | RcppExport SEXP calcWTilda(SEXP wTildaTransposes, SEXP Ds) ;
      | ^~~~~~~~~~
calcBATS.h:44:1: error: ‘RcppExport’ does not name a type
   44 | RcppExport SEXP makeBATSWMatrix(SEXP smallPhi_s, SEXP sPeriods_s, SEXP arCoefs_s, SEXP maCoefs_s) ;
      | ^~~~~~~~~~
calcBATS.h:46:1: error: ‘RcppExport’ does not name a type
   46 | RcppExport SEXP makeBATSGMatrix(SEXP alpha_s, SEXP beta_s, SEXP gammaVector_s, SEXP seasonalPeriods_s, SEXP p_s, SEXP q_s) ;
      | ^~~~~~~~~~
calcBATS.h:48:1: error: ‘RcppExport’ does not name a type
   48 | RcppExport SEXP updateFMatrix(SEXP F_s, SEXP smallPhi_s, SEXP alpha_s, SEXP beta_s, SEXP gammaBold_s, SEXP ar_s, SEXP ma_s, SEXP tau_s) ;
      | ^~~~~~~~~~
calcBATS.h:50:1: error: ‘RcppExport’ does not name a type
   50 | RcppExport SEXP updateWtransposeMatrix(SEXP wTranspose_s, SEXP smallPhi_s, SEXP tau_s, SEXP arCoefs_s, SEXP maCoefs_s, SEXP p_s, SEXP q_s) ;
      | ^~~~~~~~~~
calcBATS.h:52:1: error: ‘RcppExport’ does not name a type
   52 | RcppExport SEXP updateGMatrix(SEXP g_s, SEXP gammaBold_s, SEXP alpha_s, SEXP beta_s, SEXP gammaVector_s, SEXP seasonalPeriods_s) ;
      | ^~~~~~~~~~
calcBATS.h:55:1: error: ‘RcppExport’ does not name a type
   55 | RcppExport SEXP makeTBATSWMatrix(SEXP smallPhi_s, SEXP kVector_s, SEXP arCoefs_s, SEXP maCoefs_s, SEXP tau_s) ;
      | ^~~~~~~~~~
calcBATS.h:57:1: error: ‘RcppExport’ does not name a type
   57 | RcppExport SEXP makeCIMatrix(SEXP k_s, SEXP m_s) ;
      | ^~~~~~~~~~
calcBATS.h:59:1: error: ‘RcppExport’ does not name a type
   59 | RcppExport SEXP makeSIMatrix(SEXP k_s, SEXP m_s) ;
      | ^~~~~~~~~~
calcBATS.h:61:1: error: ‘RcppExport’ does not name a type
   61 | RcppExport SEXP makeAIMatrix(SEXP C_s, SEXP S_s, SEXP k_s) ;
      | ^~~~~~~~~~
calcBATS.h:63:1: error: ‘RcppExport’ does not name a type
   63 | RcppExport SEXP updateTBATSGammaBold(SEXP gammaBold_s, SEXP kVector_s, SEXP gammaOne_s, SEXP gammaTwo_s) ;
      | ^~~~~~~~~~
calcBATS.h:65:1: error: ‘RcppExport’ does not name a type
   65 | RcppExport SEXP updateTBATSGMatrix(SEXP g_s, SEXP gammaBold_s, SEXP alpha_s, SEXP beta_s) ;
      | ^~~~~~~~~~
calcBATS.h:67:1: error: ‘RcppExport’ does not name a type
   67 | RcppExport SEXP calcTBATSFaster(SEXP ys, SEXP yHats, SEXP wTransposes, SEXP Fs, SEXP xs, SEXP gs, SEXP es, SEXP xNought_s) ;
      | ^~~~~~~~~~
calcBATS.cpp:3:17: error: ‘Rcpp’ is not a namespace-name
    3 | using namespace Rcpp ;
      |                 ^~~~
calcBATS.cpp:5:1: error: ‘SEXP’ does not name a type
    5 | SEXP calcBATS(SEXP ys, SEXP yHats, SEXP wTransposes, SEXP Fs, SEXP xs, SEXP gs, SEXP es ){
      | ^~~~
calcBATS.cpp:42:1: error: ‘SEXP’ does not name a type
   42 | SEXP calcBATSFaster(SEXP ys, SEXP yHats, SEXP wTransposes, SEXP Fs, SEXP xs, SEXP gs, SEXP es, SEXP xNought_s, SEXP sPeriods_s, SEXP betaV, SEXP tau_s, SEXP p_s, SEXP q_s ) {
      | ^~~~
calcBATS.cpp:258:1: error: ‘SEXP’ does not name a type
  258 | SEXP calcWTilda(SEXP wTildaTransposes, SEXP Ds) {
      | ^~~~
make: *** [/usr/lib/R/etc/Makeconf:177: calcBATS.o] Error 1

**Comment by eddelbuettel** [comment] 2023-03-31 04:39
Ok, it's late here -- but if Rob's `forecast` fails to build for you (and I note that this is a reliable package that has worked for years) why is that an error in `Rcpp` ?

**Comment by eddelbuettel** [comment] 2023-03-31 04:52
I just did the following:

```sh
$ docker run --rm -ti rocker/r-base     # standard R 4.2.3, in this case on Debian
R> install.packages("forecast")
.... goes off for a few minutes as `forecast` has quite the tail of depedencies ...
.... errors because `curl` needed a header so that stops so I `system("apt update -qq && apt install r-cran-curl")`
... followed by another 
R> install.packages("forecast")
R> library(forecast)
```

so it all works.   Even better for Ubuntu systems: [r2u](https://eddelbuettel.github.io/r2u/).  Here is quick demo -- taking all of eleven seconds:

![forecast_2023-03-30_23-49](https://user-images.githubusercontent.com/673121/229025535-29c6e138-4eef-48c8-b0de-efc5e8145e88.gif)

In short, I see no Rcpp issue.  If you have one _that is reproducible on current systems_ and _does not contradict the perfect status of `forecast` at CRAN_ (see https://cloud.r-project.org/web/checks/check_results_forecast.html) I would be all ears and you should re-open this.  Until then I think we can close this.

**Comment by eddelbuettel** [comment] 2023-03-31 04:58
Also, as you are on PopOS which should be close enough to Ubuntu: you can run r2u on your system. It is just a matter of adding new repos for both R itself (from CRAN) and r2u -- and then you _all_ of CRAN as binaries.  Give it a read at https://eddelbuettel.github.io/r2u/

I close this now.

**Closed by eddelbuettel** 2023-03-31 04:58 UTC

**Comment by alejandrohagan** [comment] 2023-03-31 18:35
hey! thanks for respoding. I installed the packages through my terminal rather than Rstudio and it managed to install everything that I needed and it works now

Regarding R 4.1 vs 4.2 its strange because when i go to install r-base it it tells me I'm using the latest r version 

Anyways, it works now so thank you

**Comment by eddelbuettel** [comment] 2023-03-31 18:37
No worries.  When an install fails it generally does not hurt to check
- what the status of the same package on the most closesely matching architecture at CRAN is 
- whether R and other packages are current because that is what CRAN uses

The results page there is good and very useful.
