### ISSUE TITLE
sprintf() warning message in MaxOS with Xcode 14.0

### ISSUE THREAD

**Issue by EnigmaSong** [RcppCore/Rcpp#1239] opened 2022-12-13 17:01 UTC
Hello,

After updating Xcode on MacOS, I have warning messages about `sprintf`  when I compile Rcpp code. The messages are just a little bit annoying even my codes work well. I am not sure [this thread](https://developer.apple.com/forums/thread/714675) and [this](https://github.com/openjdk/jdk/pull/11115) would be related to the issue. 

Any Rcpp code generates the warning, but here is an example code.

```
library(Rcpp)
set.seed(2021)

n = 300
p = 50

X <- matrix(rnorm(n*p), n, p)
Y <- rnorm(n)

arma_naive <- cppFunction('arma::mat naive2(const arma::mat &X, const arma::vec &Y){
  return (inv(X.t()*X)*(X.t()*Y));
}
', depends = "RcppArmadillo")

system.time(arma_naive(X,Y))

sessionInfo()
```

Here are the warning messages and sessionInfo():
```
In file included from file951e4fa2c48d.cpp:3:
In file included from /Users/user/Library/R_libs/RcppArmadillo/include/RcppArmadillo.h:29:
In file included from /Users/user/Library/R_libs/RcppArmadillo/include/RcppArmadillo/interface/RcppArmadilloForward.h:25:
In file included from /Users/user/Library/R_libs/Rcpp/include/RcppCommon.h:168:
/Users/user/Library/R_libs/Rcpp/include/Rcpp/internal/r_coerce.h:255:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
    ::sprintf(buff, "%02x", from);
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 warning generated.
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: could not create compact unwind for ___emutls_get_address: registers 23 and 24 not saved contiguously in frame
   user  system elapsed 
      0       0       0 
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.9

loaded via a namespace (and not attached):
[1] compiler_4.2.1           tools_4.2.1              RcppArmadillo_0.11.4.2.1
```

And this is the compiler version I'm using.
```
$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Thank you!

**Comment by eddelbuettel** [comment] 2022-12-13 17:02
Please see the commit log, that is already fixed in Rcpp -- and you can get an interim release from the `drat` repo.  Let me know if you need more helps.

**Comment by EnigmaSong** [comment] 2022-12-13 17:07
Thank you! I have checked [the commit log](https://github.com/RcppCore/Rcpp/commit/52bfbacae36fffa51b6a320f091671a673406b4b) and [drat](https://github.com/RcppCore/drat) repo. I hope the updated version will be available on CRAN soon.

**Comment by eddelbuettel** [comment] 2022-12-13 17:08
Great.

And yes we update twice a year (in Jan and Jul, usually) but you always have the drat repo.

**Closed by eddelbuettel** 2022-12-13 17:08 UTC

**Comment by eddelbuettel** [comment] 2022-12-13 20:31
I was a little tied up with calls earlier, so apologies for the very brief replies.  The issue is know, and valud -- but also addressed in the repo.  Sometimes when you are handed a new compiler with new warning you may also have to resort (at least temporarily) to new options to suppress the warnings.  Rcpp has such a large footprints that we have to be conservative about update. I hope you understand the reasoning.

**Comment by EnigmaSong** [comment] 2022-12-13 20:51
Thank you very much for the explanation. I fully understand it.
