### ISSUE TITLE
Extend the supported number of ctor arguments.

### ISSUE THREAD

**Issue by Gawainus** [RcppCore/Rcpp#1106] opened 2020-07-21 17:23 UTC
Hi, this is my first attempt to contribute to Rcpp. I followed the wiki and stackoverflow instructions. And did not find a way to support more than 8 numbers of arguments that can be passed in to the ctor. I have prepared a change locally and would like to create a PR.

[`Module_generated_Constructor`](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/module/Module_generated_Constructor.h) and related files need to be change to be able to support more arguments.

```
template <typename Class, typename U0, typename U1, typename U2, typename U3, typename U4, typename U5, typename U6, typename U7 >
class Constructor_8 : public Constructor_Base<Class>{
```

**Comment by eddelbuettel** [comment] 2020-07-21 17:27
Constructor for _what_ ?  Can you share an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) of what you are trying to do?

Because we still cater to the least common denominator, this code is macro generated and capped in numbers. But because you can endlessly nest elements within `Rcpp::List` objects, it is not really a binding constraint.

We have shown how to work around it with nested `Rcpp::List` calls either here or on StackOverflow so this isn't really a new issue, or actual requirement.  Unless I am missing something in which case I would ask you to expand your question.

**Comment by Gawainus** [comment] 2020-07-23 14:17
Thanks for the reply. We would like to do something like the following. Since Rcpp supports only up to 7 arguments, it is a bit unnatural to bind a c++ ctor with more than 7 arguments. As you suggested, there are ways to get around it. But my wish is to raise the cap. To me personally, 7 seems a bit limited, unless there are other implications that I am not aware of.

```C++
RCPP_MODULE(myMod) {
    class_<MyClass>("MyClass")
        .constructor<U0, U1,...U8> ();
}
```

**Comment by eddelbuettel** [comment] 2020-07-23 14:24
Sure.  I would, however, suggest you do this locally.

Rcpp is used by over 2000 packages on CRAN.  The API you are looking at has essentially functioned as is for (give or take) a decade.  Making changes requires _extensive_ testing on our end.  As it currently stands, this change request does not meet the criterion.   But maybe if you work on it locally, test and refine and demonstrate that it has no ill effects on the 2000 CRAN packages using Rcpp (and hence "hopefully" the likely even larger number of non-CRAN packages) we can revisit.

**Comment by Gawainus** [comment] 2020-07-23 14:42
Thanks. This makes sense. Is there testing guideline that I can follow, meaning testing the 2000 CRAN packages? Or simply pull all of them and test them against my change?

**Comment by eddelbuettel** [comment] 2020-07-23 14:46
It's not easy. I have access to a dedicated (old) machine where I do that.  Part of the work is setting this up, part of the work is going through the logs to identify failures. 

Also, if I may, I still don't understand why you need it. It's for Rcpp Modules.  Wrapping _simple_ structures.  Can you not have an simpler constructor followed by a number of value setters?

**Comment by Gawainus** [comment] 2020-07-25 16:37
Interesting. Like a physical machine? If I may suggest, we should have a bit more clear guideline of setting up these tests, so that new people like myself can jump in and contribute. Maybe a docker image?

That's true. Either pack arguments in a dictionary or use setters would work. My intention is a bit more simple, to have the same ctor signature in Rcpp and C++. This is not a limitation in Pybind11. And 7 does seem to be a bit small. That's why I thought it might be a good idea to raise the cap.

**Comment by eddelbuettel** [comment] 2020-07-25 16:52
1. See maybe _Writing R Extensions_ for general information as there is some support in base R for reverse dependency checking though I keep forgetting the name of the function.  I wrote a package for this too which I happen to use now:  [prrd](https://github.com/eddelbuettel/prrd)

2. The comparison to Pybind11 is interesting but not relevant. Rcpp Modules has a defined and limited scope for, as I said, wrapping _simple_ structures.  For more complex work there are no (or different) limitations in Rcpp.

Hence, I suggested we close this now.  If and when you have a more refined proposal please feel free to come back and reopen.

Thanks for your understanding.

**Closed by eddelbuettel** 2020-07-25 16:52 UTC
