### ISSUE TITLE
sourceCpp changes working directory

### ISSUE THREAD

**Issue by kendonB** [RcppCore/Rcpp#309] opened 2015-06-23 22:36 UTC
I don't think this should be happening. I run something like:

    sourceCpp("C/foo.cpp")

and the new wd is ``"old_folder/C"``

Hope this helps!

**Comment by eddelbuettel** [comment] 2015-06-24 04:58
What version of Rcpp and what OS?   It does not happen here:

```r
R> library(Rcpp)
R> getwd()
[1] "/home/edd/Dropbox/src/R"
R> sourceCpp("/tmp/alexios.cpp")
R> getwd()
[1] "/home/edd/Dropbox/src/R"
R> 
```

and it is not a relative-vs-absolute path issue:

```r
R> setwd("~/git/src-latex/conferences/uzuerich_2015/")
R> getwd()
[1] "/home/edd/git/src-latex/conferences/uzuerich_2015"
R> sourceCpp("code/cumsum.cpp")
R> getwd()
[1] "/home/edd/git/src-latex/conferences/uzuerich_2015"
R> 
```

**Comment by kendonB** [comment] 2015-06-24 21:53
I've recently upgraded from Rcpp 0.11.3 to 0.11.5 and the problem seems to no longer occur.

**Comment by gforge** [comment] 2015-08-02 06:33
I'm not sure this should be closed - I'm currently experiencing the same issue when running on my Win 8.1 machine with Rcpp 0.12.0 and R 3.2.1

**Comment by jjallaire** [comment] 2015-08-02 11:17
I'm not able to reproduce this locally (Rcpp 0.12.0, and R 3.2.1 on both Win7 and OS X Mavericks). Could you provide a full reproducible example including the source file you are compiling, the exact call to sourceCpp, and the working directory before and after the compilation.

**Comment by gforge** [comment] 2015-08-02 13:12
Wow this was a little tricky once I digged a little deeper. It **only** appears after sourceCpp the same file **twice**!? I.e. the following code causes the error:

```R
library(Rcpp)
getwd()
sourceCpp("C:/Users/Max/Documents/R/test/cpp/test.cpp")
getwd()
sourceCpp("C:/Users/Max/Documents/R/test/cpp/test.cpp")
getwd()
```

Gives the following:

```R
> library(Rcpp)
> getwd()
[1] "C:/Users/Max/Documents/R/test"
> sourceCpp("C:/Users/Max/Documents/R/test/cpp/test.cpp")

> timesTwo(42)
[1] 84
> getwd()
[1] "C:/Users/Max/Documents/R/test"
> sourceCpp("C:/Users/Max/Documents/R/test/cpp/test.cpp")

> timesTwo(42)
[1] 84
> getwd()
[1] "C:/Users/Max/Documents/R/test/cpp"
```

It seems independent of the test-file, I'm currently compiling the default file from RStudio:

```C
#include <Rcpp.h>
using namespace Rcpp;

// This is a simple example of exporting a C++ function to R. You can
// source this function into an R session using the Rcpp::sourceCpp 
// function (or via the Source button on the editor toolbar). Learn
// more about Rcpp at:
//
//   http://www.rcpp.org/
//   http://adv-r.had.co.nz/Rcpp.html
//   http://gallery.rcpp.org/
//

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}


// You can include R code blocks in C++ files processed with sourceCpp
// (useful for testing and development). The R code will be automatically 
// run after the compilation.
//

/*** R
timesTwo(42)
*/
```

I've by the way just upgraded to Windows 10. Also doing an `rm(list = ls())` does not affect the result.

**Comment by eddelbuettel** [comment] 2015-08-02 13:27
Yes, also seeing this on Linux with 0.12.0.  I create `timesTwo.cpp` via RStudio, and explicitly save it somewhere with enough directories.  

```
R> library(Rcpp)
R> getwd()               # still good
[1] "/home/edd"
R> sourceCpp("/tmp/some/more/directories/timesTwo.cpp")

R> timesTwo(42)
[1] 84
R> getwd()               # still good     
[1] "/home/edd"
R> sourceCpp("/tmp/some/more/directories/timesTwo.cpp")

R> timesTwo(42)
[1] 84
R> getwd()              # now changed
[1] "/tmp/some/more/directories"
R> 
```

**Comment by eddelbuettel** [comment] 2015-08-02 13:38
Appears to be from this bit (here with a debugging line I added):

```r
    # source the embeddedR
    if (embeddedR && (length(context$embeddedR) > 0)) {
        srcConn <- textConnection(context$embeddedR)
        cat("D Setwd to ", rWorkingDir, "\n")
        setwd(rWorkingDir) # will be reset by previous on.exit handler
        source(file=srcConn, echo=TRUE)
    }
```

Could it be that we do not have an `on.exit()` in this case of a non-rebuild?

**Comment by jjallaire** [comment] 2015-08-03 10:07
This has now been fixed on master via
https://github.com/RcppCore/Rcpp/commit/f9ae86b6c9d8a19fc78711f033f1e48cb4d7ff03

**Closed** 2015-08-03 11:49 UTC
