### ISSUE TITLE
Should be possible change function parameters names?

### ISSUE THREAD

**Issue by rspadim** [RcppCore/Rcpp#1214] opened 2022-04-26 20:29 UTC
Hello I have a function at rcpp that i want to change the name of parameters:

I want that degree_x become degree.x (with dot) at R world

```
//' Divergent-Upper Partial Moment
//' (Upper Left Quadrant 2)
//'
//' This function generates a divergent upper partial moment between two equal length variables for any degree or target.
//' @param degree.x integer; Degree for variable X.  \code{(degree.x = 0)} is frequency, \code{(degree.x = 1)} is area.
//' @param degree.y integer; Degree for variable Y.  \code{(degree.y = 0)} is frequency, \code{(degree.y = 1)} is area.
//' @param x a numeric vector.
//' @param y a numeric vector of equal length to \code{x}.
//' @param target.x numeric; Typically the mean of Variable X for classical statistics equivalences, but does not have to be. (Vectorized)
//' @param target.y numeric; Typically the mean of Variable Y for classical statistics equivalences, but does not have to be. (Vectorized)
//' @return Divergent UPM of two variables
//' @author Fred Viole, OVVO Financial Systems
//' @references Viole, F. and Nawrocki, D. (2013) "Nonlinear Nonparametric Statistics: Using Partial Moments"
//' \url{https://www.amazon.com/dp/1490523995/ref=cm_sw_su_dp}
//' @examples
//' set.seed(123)
//' x <- rnorm(100) ; y <- rnorm(100)
//' D.UPM(0, 0, x, y, mean(x), mean(y))
//' @export
// [[Rcpp::export("D.UPM", rng = false)]]
NumericVector DUPM_CPv(
    const double degree_x, const double degree_y, 
    const NumericVector x, const NumericVector y, 
    const NumericVector target_x, const NumericVector target_y
) {
  size_t target_x_size=target_x.size();
  size_t target_y_size=target_y.size();
  size_t max_target_size=(target_x_size>target_y_size?target_x_size:target_y_size);
  NumericVector output = NumericVector(max_target_size);
  DUPM_Worker tmp_func(degree_x, degree_y, x, y, target_x, target_y, output);
  parallelFor(0, output.size(), tmp_func);
  return(output);
}
```

**Comment by eddelbuettel** [comment] 2022-04-26 20:32
I think you cannot as _interface_ parameters have to exist in _both_ languages and a dot is not a permitted part of a variable name.

**Comment by rspadim** [comment] 2022-04-26 21:10
could we change it at RcppExports.R file?

**Comment by eddelbuettel** [comment] 2022-04-26 21:13
If by "we" you mean "@rspadim could possibly work on a PR that adds this added complexity" sure. We cannot stop you.  But you may have an uphill battle to convince us is that it is needed or a reasonable idea ...

I would just export the C++ file to a different name (you already do that) to have something that is R callable. And then add another R function to call it and remamed / copy variable as you seem to require.

**Comment by rspadim** [comment] 2022-04-26 21:31
ok, i was thinking that the .R file couldn't be changed, well it's easier to just replace the variable names here
i was porting a R function to Rcpp, that's why i want to use the same variable name

**Comment by rspadim** [comment] 2022-04-26 21:33
is there any place to ask about problems with Rcpp + package build? I'm trying to use the funciton but i don't know where to ask about this kind of error ""_NNS_CoLPM_CPv" not available for .Call() for package "NNS""

i'm at https://github.com/OVVO-Financial/NNS/tree/spadim_rcpp doing devtools::check()

**Comment by eddelbuettel** [comment] 2022-04-26 21:36
I think this has come before, feel free to search the Issues tab here.   Sometimes the binding constraints as for example "identifiers much work in both languages" force us to work with subsets of features in _one_ language to make the interop possible.  And _theoretically_ what you suggest may be possible but nobody on Team Rcpp thinks the file `src/attributes.cpp` -- which is already at 3760 lines -- should be made any more complex because of an issue as small as this which has possible workarounds. 

So I am going to close this.  If you feel you have good and convincing arguments to change our mind feel free to reopen.

(As for "where to ask": the Rcpp documentation is quite plain about the existence of a dedicated mailing list for just that, Subscribe, and post there. Preferably with reproducible code.)

**Closed by eddelbuettel** 2022-04-26 21:36 UTC

**Comment by eddelbuettel** [comment] 2022-04-26 21:48
PS An error such as `"_NNS_CoLPM_CPv" not available for .Call() for package "NNS"` usually means you got yourself tied in a know between what you define and what has been mapped.  _Personally speaking_ I prefer more direct control so my cycle is

- edit file
- call `compileAttributes()` (which RStudio calls for you automagically unless you unset it)
- build tarball
- install tarball

and I sometimes take shortcuts of skipping the tarball.   But when the linker says 'symbol "foobar123" not found" start by grepping whether you have a symbol, whether it is exported and visible, whether your `NAMESPACE` file is right etc pp.  If in doubt start from an empty package (via `Rcpp.package,skeleton()` and re-add one function at a time).  Eventual you will notice which small (but important) step you may have skipped.  There are not shortcut. and there still is no free lunch.
