### ISSUE TITLE
Undefined Symbol Error: Established solutions not working

### ISSUE THREAD

**Issue by AnnabelPerry** [RcppCore/Rcpp#1169] opened 2021-08-11 17:24 UTC
I know you've gotten a lot of questions regarding "undefined symbol" errors through StackOverflow, the Rcpp mailing list archives, and GitHub, but I've been stuck on this for over a month and have tried the answers provided through these platforms and, for some reason, they are not working on my package.

To start, I am creating an R package called Polly using Rcpp. I wrote the source code (`Polly.cpp`, see end of post for minimal example), which requires the external library HTSlib. I am using a `Makevars.in` and `configure.ac` (see end of post for minimal examples) to link my program to this library.

When I click "Check" in RStudio, I get this error:
`
Error in dyn.load(dllfile) :    unable to load shared object '/home/annabelperry/R/Polly/src/Polly.so':   /home/annabelperry/R/Polly/src/Polly.so: undefined symbol: SSLv23_client_method Calls: <Anonymous> ... <Anonymous> -> load_dll -> library.dynam2 -> dyn.load Execution halted 
`

I have previously gotten identical undefined symbol errors for the symbols "curl_easy_perform", "MD5_Init", "SSL_alert_desc_string_long", and "SRP_create_verifier_BN"
I solved the first 3 by linking to cURL, crypto (from OpenSSL), then ssl (from OpenSSL), then solved the 4th by rearranging the  flags in `Makevars.in`. To troubleshoot the current "undefined symbol" error, I have tried every possible combination of input arrangements in the *_LIBS and *_CFLAGS fields of my current `Makevars.in`. Each permutation simply gives one of the previously mentioned "undefined symbol" errors.

I tried your answer [here ](https://stackoverflow.com/questions/36232051/rcpp-unable-to-load-shared-object-undefined-symbol) by adjusting my configure.ac script to read as follows:

`
AC_INIT([Polly], 0.1.0)`
`AC_PATH_PROG([HTS_CONFIG], [hts-config])`
`if test "${HTS_CONFIG}" != ""; then`
    `HTS_CFLAGS=`${HTS_CONFIG} --cflags``
    `HTS_LIBS=`${HTS_CONFIG} --libs``
`else`
    `AC_MSG_ERROR([hts-config not found, is HTS installed?])`
`fi`
`AC_PATH_PROG([CURL_CONFIG], [curl-config])`
`if test "${CURL_CONFIG}" != ""; then`
`    CURL_CFLAGS=`${CURL_CONFIG} --cflags``
`    CURL_LIBS=`${CURL_CONFIG} --libs``
`else`
`    AC_MSG_ERROR([curl-config not found, is CURL installed?])`
`fi`
`AC_PATH_PROG([SSL_CONFIG], [ssl-config])`
`if test "${SSL_CONFIG}" != ""; then`
`    SSL_CFLAGS=`${SSL_CONFIG} --cflags``
`    SSL_LIBS=`${SSL_CONFIG} --libs``
`else`
`    AC_MSG_ERROR([ssl-config not found, is SSL installed?])`
`fi`
`AC_PATH_PROG([CRYPTO_CONFIG], [crypto-config])`
`if test "${CRYPTO_CONFIG}" != ""; then`
`    CRYPTO_CFLAGS=`${CRYPTO_CONFIG} --cflags``
`    CRYPTO_LIBS=`${CRYPTO_CONFIG} --libs``
`else`
`    AC_MSG_ERROR([crypto-config not found, is CRYPTO installed?])`
`fi`
`AC_SUBST(HTS_CFLAGS)`
`AC_SUBST(HTS_LIBS)`
`AC_SUBST(CURL_CFLAGS)`
`AC_SUBST(CURL_LIBS)`
`AC_SUBST(SSL_CFLAGS)`
`AC_SUBST(SSL_LIBS)`
`AC_SUBST(CRYPTO_CFLAGS)`
`AC_SUBST(CRYPTO_LIBS)`
`AC_OUTPUT(Makevars)`

...but I just got the following error upon running `autoconf` in my `src/` directory:
`
configure: error: hts-config not found, is HTS installed?
`

I have tried rerunning compileAttributes() and even re-building my package (see end of post for exact steps on how I originally built my package), as you indicated in a previous post that moving around files may cause `RcppExports.R` to be out-of-sync. This did not solve the issue.

Here are the _minimal_ versions of each of the relevant files from the `src/` and `R/` directories:
### Polly/src
Polly.cpp

```
#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <iterator>
#include <regex>
#include <limits>
#include <map>
#include <stdlib.h>
#include <bits/stdc++.h>
#include "sam.h"
#include <Rcpp.h>
#include "Polly.h"

void Test(std::string input){
  const char * char_bam;
  char_bam = input.c_str();
  samFile *bam_file = sam_open(char_bam, "r");
}
```

Polly.h
```
#ifndef TEST_H
#define TEST_H

//' Documentation
//' @param input A function
// [[Rcpp::export]]
void Test(std::string input);

#endif // TEST_H
```

configure.ac
```
#                                               -*- Autoconf -*-
# Process this file with autoconf to produce a configure script.

AC_INIT([Polly], 0.1.0)

AC_LANG(C++)
AC_REQUIRE_CPP 
AC_PROG_CXX  

# Checks for common programs using default macros
AC_PROG_CC

# default values 
AC_SUBST([HTS_CFLAGS], "-I/sw/eb/sw/HTSlib/1.10.2-GCC-8.3.0/include/htslib/") 
AC_SUBST([HTS_LIBS], "/sw/eb/sw/HTSlib/1.10.2-GCC-8.3.0/lib/libhts.a")
AC_SUBST([CURL_CFLAGS], "-I/sw/eb/sw/cURL/7.66.0-GCCcore-8.3.0/include/curl/") 
AC_SUBST([CURL_LIBS], "/sw/eb/sw/cURL/7.66.0-GCCcore-8.3.0/lib/libcurl.a")
AC_SUBST([SSL_CFLAGS], "-I/sw/eb/sw/OpenSSL/1.1.1d-GCCcore-8.3.0/include/openssl/") 
AC_SUBST([SSL_LIBS], "/sw/eb/sw/OpenSSL/1.1.1d-GCCcore-8.3.0/lib/libssl.a")
AC_SUBST([CRYPTO_CFLAGS], "-I/sw/eb/sw/OpenSSL/1.1.1d-GCCcore-8.3.0/include/openssl/") 
AC_SUBST([CRYPTO_LIBS], "/sw/eb/sw/OpenSSL/1.1.1d-GCCcore-8.3.0/lib/libcrypto.a")  

# allow for override 
AC_ARG_WITH([hts],
             AC_HELP_STRING([--with-hts=PREFIX],
                            [path where hts is installed]),
             [
              HTS_CFLAGS="-I${with_hts}/include/htslib/"
              HTS_LIBS="${with_hts}/lib/libhts.a"
             ],
             [])
AC_ARG_WITH([curl],
             AC_HELP_STRING([--with-curl=PREFIX],
                            [path where curl is installed]),
             [
              CURL_CFLAGS="-I${with_curl}/include/curl/"
              CURL_LIBS="${with_curl}/lib/libcurl.a"
             ],
             [])
AC_ARG_WITH([ssl],
             AC_HELP_STRING([--with-ssl=PREFIX],
                            [path where ssl is installed]),
             [
              SSL_CFLAGS="-I${with_ssl}/include/openssl"
              SSL_LIBS="${with_ssl}/lib/libssl.a"
             ],
             [])
AC_ARG_WITH([crypto],
             AC_HELP_STRING([--with-crypto=PREFIX],
                            [path where crypto is installed]),
             [
              CRYPTO_CFLAGS="-I${with_crypto}/include/openssl"
              CRYPTO_LIBS="${with_crypto}/lib/libcrypto.a"
             ],
             [])
# create and report output 
AC_CONFIG_FILES([Makevars]) 
AC_OUTPUT 
echo 
echo "Final Makevars" 
cat Makevars
AC_OUTPUT
```

Makevars.in
```

HTS_CFLAGS = @HTS_CFLAGS@
HTS_LIBS = @HTS_LIBS@
CURL_CFLAGS = @CURL_CFLAGS@
CURL_LIBS = @CURL_LIBS@
SSL_CFLAGS = @SSL_CFLAGS@
SSL_LIBS = @SSL_LIBS@
CRYPTO_CFLAGS = @CRYPTO_CFLAGS@
CRYPTO_LIBS = @CRYPTO_LIBS@


PKG_CPPFLAGS = $(HTS_CFLAGS) $(CURL_CFLAGS) $(SSL_CFLAGS) $(CRYPTO_CFLAGS)
PKG_LIBS = $(HTS_LIBS) $(CURL_LIBS) $(SSL_LIBS) $(CRYPTO_LIBS) 
```

### Polly/R ###
Polly-package.R
```

## usethis namespace: start
#' @useDynLib Polly, .registration = TRUE
## usethis namespace: end
NULL

## usethis namespace: start
#' @importFrom Rcpp sourceCpp
## usethis namespace: end
NULL

#' Documentation
#' @export
Test <- function(input) {
  invisible(.Call(`_Polly_Test`, input))
}
```

To build the package, I performed the following steps in RStudio:
1. New Project -> R Package -> Package name: Polly -> Create Project
2. Add "**GPL-3**" under "License" in Description
3. Tools -> Project Options -> Build Tools -> Check "Generate documentation using **ROxygen**" -> Ok
4. Remove existing NAMESPACE and hello.rd
5. **Copy-and-paste** "Polly-package.R" script from **existing** R script to "hello.R" and change name of "hello.R" to "Polly-package.R"
6. Add documentation to "Polly-package.R"
7. Run `usethis::use_rcpp()` in RStudio command prompt
8. Copy-and-paste indicated text to "Polly-package.R"
9. Add "Polly.h" and "Polly.cpp" files, described above, to `src/` directory
10. Document
To create/run the configure script, I performed the following steps using my terminal in the `Polly/src/` directory:
1. autoconf
2. ./configure
I then navigated back to RStudio and checked the package, getting the previously-described error.

I am running all my code on my institution's (Texas A&M University) supercomputer clusters. I use a VPN to access the clusters remotely from my laptop.

Here are the details of the supercomputer cluster terminal (obtained by running `lsb_release -a`):
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

I am using RStudio 4.0.3

**Comment by eddelbuettel** [comment] 2021-08-11 17:29
You are using a GitHub account, but I see no code repository.  Is your code publically accessible somewhere so that we can help?

If not, can you _please_ create a minmally reproducible example (by starting from, say, `Rcpp.package.skeleton()` and then adding one access to `polly`) ?

**Comment by eddelbuettel** [comment] 2021-08-11 18:58
Also, I replied to both your StackOverflow posts, and in one also recommended you look at the [existing Bioconductor package Rhtslib](https://bioconductor.org/packages/release/bioc/html/Rhtslib.html)

You have not really engaged with the answers at StackOverflow, and now you appear to have the same content here.  

Has anything changed?  What have you learned?  What are you stuck?  Dropping one hundred lines on people (with non-reproducible code unless we sit down and piece it all together) may be asking too much from volunteers.  

At the outset, you seem to have decided to use autoconf to create `configure` to check for the HTS library.  That is a good plan.  But had you noticed `configure: error: hts-config not found, is HTS installed?` ?  If there is no `hts-config` you cannot rely on it to query for HTS.  All this is ... really an autoconf question.  Happy to help, but an Rcpp ticket is not really the right place.  I have written quite a few such `configure.ac` for autoconf myself but my suggestions to you to please study existing solutions went nowhere so ....

**Comment by eddelbuettel** [comment] 2021-08-11 19:25
Here is $0.02.  On the systems I use, `hts-config` does not seem to exist.  But the (more general) `pkg-config` can be queries for HTS.  So on a mostly empty Docker container with `libhts-dev` installed I see

```sh
root:~# pkg-config --cflags htslib

root:~# pkg-config --libs htslib
-lhts
root:~# 
```

This tells us that a) not CFLAGS for `-I` are needed as the headers are in a standard location (possibly different on your cluster) and b) similarly we do not need any -L flags for LIBS but simply `-lhts`.

That, in sum, could really not be any easier.  You need to

1. query for pkg-config and error out if not found
2. query pkg-config to see if it has HTS information
3. use pkg-config --cflags and use that
4. use pkg-config --libs and use that

There will be many packages doing very similar things with other (very public) libraries for png, xml, ...   Hope this helps.

**Comment by AnnabelPerry** [comment] 2021-08-12 01:23
I'm sorry for being a bother - I'm an undergrad and I only started using R
and C++ last year.  My PI doesn't know how to code, and I'm the only person
in my lab who uses C++. so I don't really have anyone to ask these
questions. I've never taken a coding class (I'm a biology major), so I've
had to figure out trouble-shooting and StackOverflow/GitHub etiquette
myself (I guess I haven't done too great a job at either of these things).
I never used GNU m4 before embarking on this project, so I'm not super
comfortable editing configure.ac files without an existing template.

Your suggestions seem to have helped (I got a new error, so at least that's
progress)

I'm sorry that I wasted your time - I understand you're extremely busy.
Best,

**Comment by eddelbuettel** [comment] 2021-08-12 01:27
Noted.  We all started young and had people help us along the way so we all pay it forward.  I _can_ try to help you, but it does not work if you drop 200 lines essays, then disappear and never respond to questions.  In short, in order for *us* to help *you* we need a bit for infomation. 

What is the ultimate goal here?  "Get some working code just on your cluster" or that, plus a possible "publication" of code to CRAN?   Also, have you tried using _the existing Bioconductor package_ for this?

**Comment by eddelbuettel** [comment] 2021-08-12 01:30
(The reason I asked the last question is that learning `configure` and `autoconf` is a little like learning a new language. If you "only" need a local solution we can take shortcuts.)

**Comment by eddelbuettel** [comment] 2021-08-12 02:04
Ok.  Split the tasks into two.  _For now_ do not treat your (to be on CRAN one day) package as generic.  Treat it as local development and _just hardwire into src/Makevars the compiler and linker flags you use on your cluster_.   I presume you know those values as you have a locally working package?

If and when you are happy with what the package does, learn about "how packages find libraries".  There are in essence three solutions:  Jeroen does a lot in shell scripts he calls "anticonf" to mock autoconf.  You could try that (look eg at his jsonlite package).  I often go the longer route via autconf, but we can also do this with shell script quering pkg-config.

And we should probably have this discussion elsewhere as none of this is Rcpp related -- it's just a bit of 'more basic software engineering for science' which your Bio dept doesn't teach you.   Is there a repo you can invite me to?

**Comment by AnnabelPerry** [comment] 2021-08-12 02:12
Ok, I'll give this a shot. I'll try to make a repository and invite you to
it!

**Comment by eddelbuettel** [comment] 2021-08-12 02:38
That worked.  Let's continue over there and close this.

**Closed by eddelbuettel** 2021-08-12 02:38 UTC
