### ISSUE TITLE
Regression in 0.12.18: type errors crash instead of error

### ISSUE THREAD

**Issue by jeroen** [RcppCore/Rcpp#888] opened 2018-07-30 18:57 UTC
After the latest Rcpp update, @sckott's crul package started [failing checks](https://cran.r-project.org/web/checks/check_results_crul.html). The problem turns out to be a unit tests which tests Rcpp type error messages like this:

```r
urltools::parameters(mtcars)
```

If `urltools` was compiled against Rcpp 0.12.17 (e.g. the `urltools` cran binary package), this yields an error. However if we recompile `urltools` against Rcpp 0.12.18, this now causes a crash.

**Comment by eddelbuettel** [comment] 2018-07-30 19:14
The `urltools` package passes every single regression test since the last release:

```
edd@rob:~/git/rcpp-logs(master)$ for q in queues/Rcpp_2018-0[67]*/queuefile.sqlite; do sqlite3 ${q} "select * from results where package='urltools';"; done
urltools|1.7.0|0|2018-06-04 00:50:21.98|2018-06-04 00:51:48.94|86.9584002494812|107129|debbuilder
urltools|1.7.0|0|2018-06-07 07:16:41.18|2018-06-07 07:18:10.28|89.100501537323|38113|debbuilder
urltools|1.7.0|0|2018-06-08 08:25:37.98|2018-06-08 08:27:06.45|88.4717009067535|69211|debbuilder
urltools|1.7.0|0|2018-06-09 23:25:54.30|2018-06-09 23:26:24.39|30.0923364162445|119680|debbuilder
urltools|1.7.0|0|2018-06-11 02:44:53.52|2018-06-11 02:46:21.54|88.0207781791687|46875|debbuilder
urltools|1.7.0|0|2018-06-12 18:29:41.95|2018-06-12 18:31:11.94|89.9960336685181|5251|debbuilder
urltools|1.7.0|0|2018-06-13 05:34:25.74|2018-06-13 05:35:53.79|88.052072763443|34219|debbuilder
urltools|1.7.0|0|2018-06-15 07:26:22.11|2018-06-15 07:27:53.15|91.0419447422028|92503|debbuilder
urltools|1.7.0|0|2018-06-22 07:54:45.67|2018-06-22 07:56:16.31|90.6446344852448|22200|debbuilder
urltools|1.7.0|0|2018-06-24 04:27:45.20|2018-06-24 04:29:14.67|89.4671247005463|66189|debbuilder
urltools|1.7.0|0|2018-06-24 23:42:30.35|2018-06-24 23:44:05.08|94.7313568592072|130353|debbuilder
urltools|1.7.0|0|2018-07-12 00:32:01.52|2018-07-12 00:32:31.38|29.8608419895172|113493|debbuilder
urltools|1.7.0|0|2018-07-12 10:24:40.69|2018-07-12 10:26:11.57|90.8733744621277|22645|debbuilder
urltools|1.7.0|0|2018-07-18 06:08:23.24|2018-07-18 06:08:57.66|34.4203987121582|74598|debbuilder
urltools|1.7.0|0|2018-07-21 21:10:16.95|2018-07-21 21:11:46.21|89.2642214298248|86975|debbuilder
urltools|1.7.0|0|2018-07-25 03:40:54.69|2018-07-25 03:41:29.33|34.6355717182159|97864|debbuilder
edd@rob:~/git/rcpp-logs(master)$
```

Field three is 'result' where 0 means no error.

Realistically, what else do you expect me to do?  I do not have resources to test recursively.  All I can suggest is to maybe fix the unit tests in `urltools` to cover whatever ails `crul`.  

I plan to close this as there is nothing minimally reproducible here.

**Comment by jeroen** [comment] 2018-07-30 19:31
I'm not blaming you, only reporting that something that used to work now crashes. Perhaps something that should be investigated.

I think what is happening is that we pass a data frame to a `Rcpp::CharacterVector` parameter. Before this would be caught by Rcpp and raise an error, but now causes a crash.

**Comment by jjallaire** [comment] 2018-07-30 19:35
We might need to narrow it down a bit more. This simple test (on OS X) doesn't yield a crash for me:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void boom(CharacterVector x) {

}

/*** R
df <- data.frame(x = 1, y = 2)
boom(df)
*/
```

**Comment by eddelbuettel** [comment] 2018-07-30 19:39
Ditto on Ubuntu:

```r
R> sourceCpp("/tmp/jj.cpp")

R> df <- data.frame(x = 1, y = 2)

R> boom(df)
Error in boom(df) : Not compatible with STRSXP: [type=list].
R>
```

**Comment by jeroen** [comment] 2018-07-30 20:03
OK it looks like the `urltools` package compiles with this in Makevars:

```make
PKG_CPPFLAGS = -UNDEBUG
```

If I comment that out, it no longer crashes. No idea why that's there.

**Comment by eddelbuettel** [comment] 2018-07-30 20:06
Documented change per PRs from @jackwasey -- with `-UNDEBUG` you now get more informative errors and traces.

That has bitten at least one other CRAN authors as I was CCed on correspondence from CRAN telling them that WRE explicitly forbids `-UNDEBUG`.  So not our issue, and closing.   Sorry for your troubles: we were tolerant on this / were not tickling now but now we are IFF you set `-UNDEBUG` which you should never do in shipped code.

**Closed by eddelbuettel** 2018-07-30 20:06 UTC

**Comment by jeroen** [comment] 2018-07-30 20:15
For reference: https://github.com/RcppCore/Rcpp/pull/860
