### ISSUE TITLE
No Rcpp::export attributes when www links (among others) appear in /**/-style comments

### ISSUE THREAD

**Issue by gagolews** [RcppCore/Rcpp#675] opened 2017-04-15 16:28 UTC
Compilation of the following source file:

```
#include <Rcpp.h>
using namespace Rcpp;

/* this is a bug: http://bugbugbug.com  */

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}
```

Ends up with the following warning:

```
Warning message:
In Rcpp::sourceCpp("/tmp/test.cpp") :
  No Rcpp::export attributes or RCPP_MODULE declarations found in source
```

Thanks for making R-C++ integration really seamless!

**Comment by gagolews** [comment] 2017-04-15 16:28
I guess a minimal reproducible buggy-comment is:

```
/* //  */
```

**Comment by eddelbuettel** [comment] 2017-04-15 16:29
What happens when you use 

```c++
// this is a bug: http://bugbugbug.com  
```

**Comment by gagolews** [comment] 2017-04-15 16:37
This only affects `/**/` - style comments.

**Comment by eddelbuettel** [comment] 2017-04-15 16:39
"Doctor, doctor, it hurts when I do this."
"Then don't do it."

We'll leave this open to remind us to make the regexp parser smarter. In the meantime, maybe stick to `//` comments when URLs with double forward slashes are embedded.

**Comment by gagolews** [comment] 2017-04-15 16:41
Jolly good.

**Comment by eddelbuettel** [comment] 2017-04-15 16:42
It's a valid bug report, of course, but luckily not too many people have been bitten.

**Comment by gagolews** [comment] 2017-04-15 16:47
On a side note, I always wondered why

```
/* [[Rcpp::export]] */
```

is not a synonym for

```
// [[Rcpp::export]]
```

**Comment by eddelbuettel** [comment] 2017-04-15 17:02
Maybe because the project is called Rcpp and not Rc ? ;-)

The parser in [src/attributes](https://github.com/RcppCore/Rcpp/blob/master/src/attributes.cpp) is open source like the rest of it. If you have an itch to scratch, and can do it in a way that does not create side effects or regressions we might very well include it...

**Comment by coatless** [comment] 2017-05-07 00:31
I haven't dug into this yet. But, I'm assuming that something is off with the regex specified [`src/attributes.cpp#L1141-L1142`](https://github.com/RcppCore/Rcpp/blob/5f20d1a95f53ae3fe83a977fcb81ed3d5dba0c4c/src/attributes.cpp#L1141-L1142):

Or one of the other regex matches is picking it up.... 


```r
"^\\s*//\\s*\\[\\[Rcpp::(\\w+)(\\(.*?\\))?\\]\\]\\s*$"
```

**Comment by eddelbuettel** [comment] 2017-05-07 00:53
There may be dragons.  Most of this is by @jjallaire , I would heed his sage advice as to what to try and not.  Over the years we added a special treatment for a forgotten corner case here or there.

This one does not strike me as terribly important. It is a bug, yes.  It should get fixed, yes.  

But a million other things also compete for attention and this is, quite frankly, not that high up on my list.

**Comment by jjallaire** [comment] 2017-05-07 11:06
I agree. I smudge but not one we should set aside the time to wipe away right now.

**Comment by coatless** [comment] 2017-05-09 21:40
In the interim, add it to the known issues section per @thirdwing ?

**Comment by thirdwing** [comment] 2017-06-25 22:12
BTW, it seems this issue has already been reported in #161

**Comment by david-cortes** [comment] 2019-07-19 21:30
Tip: this can be fixed by adding a further comment with `/* */` below, e.g.
```cpp
#include <Rcpp.h>
using namespace Rcpp;

/*	This will introduce a problem
	https://github.com/RcppCore/Rcpp/issues/978 */
/* this fixes it */
// [[Rcpp::export]]
List rcpp_hello_world() {

    CharacterVector x = CharacterVector::create( "foo", "bar" )  ;
    NumericVector y   = NumericVector::create( 0.0, 1.0 ) ;
    List z            = List::create( x, y ) ;

    return z ;
}
```

**Closed** 2021-01-23 02:53 UTC
Labels: documentation, lower_priority, no-issue-activity
